### ISSUE TITLE
AttributeError: 'AttrDict' object has no attribute 'use_phonemes'

### ISSUE THREAD

**Issue by tsungruihon** [mozilla/TTS#109]
When i run `train.py` file, it outputs this error:
```
(pytorch) gowild@R730:~/peter/TTS$ python train.py --config_path config_test.json --data_path /data/peter/LJSpeech-1.1/ | tee training.log
Traceback (most recent call last):
  File "train.py", line 498, in <module>
    main(args)
  File "train.py", line 359, in main
    num_chars = len(phonemes) if c.use_phonemes else len(symbols)
AttributeError: 'AttrDict' object has no attribute 'use_phonemes'
```

**Comment by erogol** [comment]
Define use_phoneme in your config_test.json file. It is true if you use phonemes or false.

**Comment by ncfausti** [comment]
What should 'audio' be set to on AttrDict in conf.json?
