### ISSUE TITLE
Lots of size mismatch errors

### ISSUE THREAD

**Issue by eiko** [mozilla/TTS#116]
I'm not sure if this is a bug or a misconfiguration on my part, but I get tons of size mismatch errors. I won't include them all unless you need them all, but here's a sample:
```
RuntimeError: Error(s) in loading state_dict for Tacotron:
	Missing key(s) in state_dict: "decoder.attention_rnn_init.weight", "decoder.memory_init.weight", "decoder.decoder_rnn_inits.weight". 
	size mismatch for embedding.weight: copying a param with shape torch.Size([149, 256]) from checkpoint, the shape in current model is torch.Size([256, 1025]).
	size mismatch for encoder.prenet.layers.0.weight: copying a param with shape torch.Size([256, 256]) from checkpoint, the shape in current model is torch.Size([256, 1025]).
	size mismatch for decoder.prenet.layers.0.weight: copying a param with shape torch.Size([256, 400]) from checkpoint, the shape in current model is torch.Size([256, 25]).
	size mismatch for decoder.proj_to_mel.weight: copying a param with shape torch.Size([400, 256]) from checkpoint, the shape in current model is torch.Size([25, 256]).
	size mismatch for decoder.proj_to_mel.bias: copying a param with shape torch.Size([400]) from checkpoint, the shape in current model is torch.Size([25]).
	size mismatch for decoder.stopnet.linear.weight: copying a param with shape torch.Size([1, 656]) from checkpoint, the shape in current model is torch.Size([1, 281]).
```

I'm running the docker image and using the TWEB model / config at: https://drive.google.com/drive/folders/1cAjRy6jB_3iwRSzkLhD6LutCTOQV28yV

Also worth mentioning that I set `use_cuda: false` because nvidia_docker isn't supported on ubuntu 18.10. Not sure if that's okay or if it breaks everything.

**Comment by gnosly** [comment]
It's working to me. Did you check out the related commit revision? Or are you using the latest one?

**Comment by eiko** [comment]
Ah I was still on the latest commit on master, changing commits fixed things. Thanks for the quick solution to my silly mistake!

**Comment by gnosly** [comment]
I met the same problem yesterday! ;)

**Comment by rnunziata** [comment]
I am having  simular issue I think. after downloading checkpoints from link
```python TacotronPlayGround.py 
 > Setting up Audio Processor...
 | > bits:20000
 | > sample_rate:80
 | > num_mels:-100
 | > min_level_db:12.5
 | > frame_shift_ms:50
 | > frame_length_ms:0.97
 | > ref_level_db:20
 | > num_freq:1025
 | > power:1.5
 | > preemphasis:None
 | > griffin_lim_iters:30
 | > signal_norm:None
 | > symmetric_norm:None
 | > mel_fmin:0
 | > mel_fmax:None
 | > max_norm:1.0
 | > clip_norm:True
 | > do_trim_silence:False
 | > n_fft:2048
 | > hop_length:4
 | > win_length:0
Traceback (most recent call last):
  File "TacotronPlayGround.py", line 85, in <module>
    model.load_state_dict(cp['model'])
  File "/home/rjn/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 719, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for Tacotron:

.
.
.
size mismatch for embedding.weight: copying a param of torch.Size([256, 1025]) from checkpoint, where the shape is torch.Size([149, 256]) in current model.
	size mismatch for encoder.prenet.layers.0.weight: copying a param of torch.Size([256, 1025]) from checkpoint, where the shape is torch.Size([256, 256]) in current model.

```

**Comment by erogol** [comment]
explained here #117

**Comment by ice16** [comment]
I have same issue about this 
RuntimeError: Error(s) in loading state_dict for Tacotron:
	size mismatch for embedding.weight: copying a param with shape torch.Size([61, 256]) from checkpoint, the shape in current model is torch.Size([129, 256]).

How to solve it?
