### ISSUE TITLE
When training in docker container, need ipc==host option

### ISSUE THREAD

**Issue by twerkmeister** [mozilla/TTS#135]
When training in a docker container the container should be started using `--ipc=host`, e.g. `docker run --runtime=nvidia --rm --entrypoint /bin/bash --ipc=host -it mozilla-tts` Otherwise the following error will occur:

```
ERROR: Unexpected bus error encountered in worker. This might be caused by insufficient shared memory (shm).
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 234, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/usr/lib/python3.6/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
  File "/usr/local/lib/python3.6/dist-packages/torch-1.0.1.post2-py3.6-linux-x86_64.egg/torch/multiprocessing/reductions.py", line 295, in reduce_storage
    fd, size = storage._share_fd_()
RuntimeError: unable to write to file </torch_5322_303039809>
```

Also see https://github.com/tengshaofeng/ResidualAttentionNetwork-pytorch/issues/2

**Comment by erogol** [comment]
Thx for pointing that out. Is it with distributed training?

**Comment by twerkmeister** [comment]
This was just using a single machine
