### ISSUE TITLE
db7f3d3 on starting server: ModuleNotFoundError: No module named 'utils'

### ISSUE THREAD

**Issue by vitaly-zdanevich** [mozilla/TTS#151]
Full error:

```
/home/vitaly_zdanevich/.local/lib/python3.6/site-packages/numba/errors.py:105: UserWarning: Insufficiently recent colorama version found. Numba requires colorama >= 0.3.9
  warnings.warn(msg)
Traceback (most recent call last):
  File "server/server.py", line 3, in <module>
    from synthesizer import Synthesizer
  File "/home/vitaly_zdanevich/TTS/server/synthesizer.py", line 8, in <module>
    from utils.text import text_to_sequence
ModuleNotFoundError: No module named 'utils'
```

**Comment by vitaly-zdanevich** [comment]
Fixed after `sudo python3 setup.py develop`
