### ISSUE TITLE
Tryin to run the server: `ModuleNotFoundError: No module named 'tkinter'`

### ISSUE THREAD

**Issue by vitaly-zdanevich** [mozilla/TTS#152]
Full message:

```
$ python3 server/server.py -c server/conf.json
/home/vitaly_zdanevich/.local/lib/python3.6/site-packages/numba/errors.py:105: UserWarning: Insufficiently recent colorama version found. Numba requires colorama >= 0.3.9
  warnings.warn(msg)
Traceback (most recent call last):
  File "server/server.py", line 3, in <module>
    from synthesizer import Synthesizer
  File "/home/vitaly_zdanevich/TTS/server/synthesizer.py", line 12, in <module>
    from matplotlib import pylab as plt
  File "/home/vitaly_zdanevich/.local/lib/python3.6/site-packages/matplotlib/pylab.py", line 257, in <module>
    from matplotlib import cbook, mlab, pyplot as plt
  File "/home/vitaly_zdanevich/.local/lib/python3.6/site-packages/matplotlib/pyplot.py", line 115, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "/home/vitaly_zdanevich/.local/lib/python3.6/site-packages/matplotlib/backends/__init__.py", line 32, in pylab_setup
    globals(),locals(),[backend_name],0)
  File "/home/vitaly_zdanevich/.local/lib/python3.6/site-packages/matplotlib/backends/backend_tkagg.py", line 6, in <module>
    from six.moves import tkinter as Tk
  File "/home/vitaly_zdanevich/.local/lib/python3.6/site-packages/six.py", line 92, in __get__
    result = self._resolve()
  File "/home/vitaly_zdanevich/.local/lib/python3.6/site-packages/six.py", line 115, in _resolve
    return _import_module(self.mod)
  File "/home/vitaly_zdanevich/.local/lib/python3.6/site-packages/six.py", line 82, in _import_module
    __import__(name)
ModuleNotFoundError: No module named 'tkinter'
```

**Comment by erogol** [comment]
It is not about TTS sorry

**Comment by vitaly-zdanevich** [comment]
For future visitors: fixed by
`sudo apt install python3-tk`
