### ISSUE TITLE
TypeError: only integer tensors of a single element can be converted to an index

### ISSUE THREAD

**Issue by aolney** [mozilla/TTS#207]
Running LJSpeech with the [recent commits](https://github.com/mozilla/TTS/commit/54f352b6719eb577181325e5152524043fb8c124) and received the following error after `train()` during epoch 0:

```
Traceback (most recent call last):
  File "train.py", line 583, in <module>
    main(args)
  File "train.py", line 470, in main
    val_loss = evaluate(model, criterion, criterion_st, ap, current_step, epoch)
  File "train.py", line 297, in evaluate
    model.forward(text_input, text_lengths, mel_input)
  File "/vm/TTS/models/tacotron2.py", line 48, in forward
    encoder_outputs, mel_specs, mask)
  File "/vm/tf-py3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/vm/TTS/layers/tacotron2.py", line 231, in forward
    mel_output, stop_token, attention_weights = self.decode(memory)
  File "/vm/TTS/layers/tacotron2.py", line 196, in decode
    self.processed_inputs, self.mask)
  File "/vm/tf-py3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/vm/TTS/layers/common_layers.py", line 250, in forward
    inputs, alignment, attention_hidden_state)
  File "/vm/TTS/layers/common_layers.py", line 210, in apply_forward_attention
    alpha[b, n + 2:] = 0
TypeError: only integer tensors of a single element can be converted to an index

```

**Comment by testpiano** [comment]
I have the same problem, 
only integer tensors of a single element can be converted to an index
there is no exact solution yet

**Comment by IveJ** [comment]
Hi issuer,

Bc of utilizing forward() in Autograd, nn module of Pytorch so this logic
wont traverse ls/dict/any other data structure and only consider Tensor
that direct argument to the call.


https://pytorch.org/docs/master/notes/extending.html

**Comment by aolney** [comment]
@testpiano Did you try the latest source? This issue was closed with commit https://github.com/mozilla/TTS/commit/f774db02414f9df5647e190d097194eafbddb080 and that solved it for me.

Perhaps you are using an incompatible version of Pytorch or some other dependency?
