### ISSUE TITLE
RuntimeError: Length of all samples has to be greater than 0, but found an element in 'lengths' that is <= 0

### ISSUE THREAD

**Issue by MuruganR96** [mozilla/TTS#220]
TWEB DATASET with Tacotron-2 archtecture.:)

```
 deprecated, please use torch.distributed.ReduceOp instead
  warnings.warn("torch.distributed.reduce_op is deprecated, please use "
tensor([[11, 30, 48, 23,  7, 38, 61, 19, 17, 16, 44, 12, 61, 20, 33, 61, 14, 16,
         44, 25, 50, 25, 55, 61, 19,  7, 38, 38, 28, 55],
        [11, 30, 48, 23,  7, 38, 61, 19, 17, 16, 44, 12, 61, 20, 33, 61, 14, 16,
         44, 25, 50, 25, 55, 61, 19,  7, 38, 38, 28, 55],
        [11, 30, 48, 23,  7, 38, 61, 19, 17, 16, 44, 12, 61, 20, 33, 61, 14, 16,
         44, 25, 50, 25, 55, 61, 19,  7, 38, 38, 28, 55],
        [11, 30, 48, 23,  7, 38, 61, 19, 17, 16, 44, 12, 61, 20, 33, 61, 14, 16,
         44, 25, 50, 25, 55, 61, 19,  7, 38, 38, 28, 55],
        [26, 14, 26, 14, 55, 61, 26, 15,  6, 61, 43, 35, 14, 33, 55, 61, 26, 15,
          6, 61, 14, 30, 48, 13, 26,  6, 33, 55,  0,  0],
        [15, 16, 44, 45, 55, 61, 43, 35, 14, 55, 61,  9, 26, 14, 55, 61, 26, 15,
          6, 61,  6, 46, 26,  8, 33, 49, 57,  0,  0,  0],
        [ 6, 26, 15, 11, 33, 13, 55, 61,  6, 46, 38, 15, 35, 49, 33, 15, 55, 61,
          5, 30, 48, 41, 45, 20, 43, 55,  0,  0,  0,  0],
        [26, 41, 33,  5, 55, 61, 26, 15,  6, 61,  6, 21, 48, 14, 33, 55, 61, 26,
         15,  6, 61, 35, 43, 33, 15, 55,  0,  0,  0,  0],
        [14, 35, 43, 33, 13, 26, 14, 55, 61, 26,  5, 38,  6, 46, 33, 55, 61, 14,
         38,  6, 46, 29, 14, 38, 15, 55,  0,  0,  0,  0],
        [14, 26, 37, 17, 38, 26, 43, 55, 61, 14, 35, 43, 33, 13, 26, 14, 55, 61,
          9, 35, 25, 38, 41, 55,  0,  0,  0,  0,  0,  0],
        [ 4, 38,  6, 16, 44, 55, 61,  6, 46, 38, 15, 38, 49, 32, 38, 55, 61, 26,
          5, 38,  6, 46, 33, 55,  0,  0,  0,  0,  0,  0],
        [61, 15, 10, 48, 27, 34, 61, 43, 26, 13, 61, 11, 21, 48, 61, 19, 20, 10,
         48, 13, 57,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [ 5, 45, 15, 10, 55, 61, 26, 25, 37, 26,  6, 55, 61,  5, 38,  5,  4, 38,
         55,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [41, 38,  6, 46, 32, 38, 19, 61, 32, 48, 13, 23,  7, 38, 25, 57,  0,  0,
          0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [27, 35, 15, 61,  6, 46, 30, 48,  5, 61, 26, 15, 19, 34,  6, 55,  0,  0,
          0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0]]) tensor([30, 30, 30, 30, 28, 27, 26, 26, 26, 24, 24, 21, 19, 16, 16,  0]) *****************
 ! Run is removed from /mnt/Murugan/TTS/tweb_models/tweb-June-22-2019_08+25AM-824c091
Traceback (most recent call last):
  File "train.py", line 555, in <module>
    main(args)
  File "train.py", line 463, in main
    ap, epoch)
  File "train.py", line 126, in train
    text_input, text_lengths,  mel_input)
  File "/mnt/Murugan/env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/mnt/Murugan/TTS/models/tacotron2.py", line 33, in forward
    encoder_outputs = self.encoder(embedded_inputs, text_lengths)
  File "/mnt/Murugan/env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/mnt/Murugan/TTS/layers/tacotron2.py", line 264, in forward
    x, input_lengths, batch_first=True)
  File "/mnt/Murugan/env/lib/python3.6/site-packages/torch/nn/utils/rnn.py", line 268, in pack_padded_sequence
    torch._C._VariableFunctions._pack_padded_sequence(input, lengths, batch_first)
RuntimeError: Length of all samples has to be greater than 0, but found an element in 'lengths' that is <= 0
Traceback (most recent call last):
  File "train.py", line 555, in <module>
    main(args)
  File "train.py", line 463, in main
    ap, epoch)
  File "train.py", line 126, in train
    text_input, text_lengths,  mel_input)
  File "/mnt/Murugan/env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/mnt/Murugan/TTS/models/tacotron2.py", line 33, in forward
    encoder_outputs = self.encoder(embedded_inputs, text_lengths)
  File "/mnt/Murugan/env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/mnt/Murugan/TTS/layers/tacotron2.py", line 264, in forward
    x, input_lengths, batch_first=True)
  File "/mnt/Murugan/env/lib/python3.6/site-packages/torch/nn/utils/rnn.py", line 268, in pack_padded_sequence
    torch._C._VariableFunctions._pack_padded_sequence(input, lengths, batch_first)
RuntimeError: Length of all samples has to be greater than 0, but found an element in 'lengths' that is <= 0

```

but TWEB DATASET sequence length for all samples > 0 .

**Comment by MuruganR96** [comment]
resolved.
i changed the condtion like this. i add **seq_len = 0** text also,

`if length < self.min_seq_len or length > self.max_seq_len
````
def sort_items(self):
        r"""Sort instances based on text length in ascending order"""
        lengths = np.array([len(ins[0]) for ins in self.items])
       
        idxs = np.argsort(lengths)
        new_items = []
        ignored = []
        for i, idx in enumerate(idxs):
            length = lengths[idx]
            if length < self.min_seq_len or length > self.max_seq_len:
                ignored.append(idx)
            else:
                new_items.append(self.items[idx])
```
