### ISSUE TITLE
ValueError: invalid literal for int() with base 10: '2a1'

### ISSUE THREAD

**Issue by wagner-daniel** [mozilla/TTS#251]
Hello,

I am trying to get TTS running on my Ubuntu 18.04 machine. I cloned the repo and checked out the commit of the current model.

I have tested every model it on my machine, in a virtual machine with a fresh install and in a docker container.

The models were the one in the server readme (with the server branche checked out), from the released models wiki page (Tacotron2-iter-260K, with commit 824c091) and I tried a build version from https://github.com/iGoog/TTSbuild

It was not always working out of box, but I managed to get the same error on every platform with every model I tried.

I even tried the old and new version of nvidia-docker, but always the same error.

When I download the model I changed the server/server.conf, to match the models and config path (inside and out of docker).

When I run the server/server.py the error occurs

```Traceback (most recent call last):
  File "server/server.py", line 3, in <module>
    from synthesizer import Synthesizer
  File "/srv/app/server/synthesizer.py", line 12, in <module>
    from matplotlib import pylab as plt
  File "/usr/local/lib/python3.6/dist-packages/matplotlib-2.0.2-py3.6-linux-x86_64.egg/matplotlib/pylab.py", line 257, in <module>
    from matplotlib import cbook, mlab, pyplot as plt
  File "/usr/local/lib/python3.6/dist-packages/matplotlib-2.0.2-py3.6-linux-x86_64.egg/matplotlib/pyplot.py", line 29, in <module>
    import matplotlib.colorbar
  File "/usr/local/lib/python3.6/dist-packages/matplotlib-2.0.2-py3.6-linux-x86_64.egg/matplotlib/colorbar.py", line 36, in <module>
    import matplotlib.contour as contour
  File "/usr/local/lib/python3.6/dist-packages/matplotlib-2.0.2-py3.6-linux-x86_64.egg/matplotlib/contour.py", line 23, in <module>
    import matplotlib.text as text
  File "/usr/local/lib/python3.6/dist-packages/matplotlib-2.0.2-py3.6-linux-x86_64.egg/matplotlib/text.py", line 33, in <module>
    from matplotlib.backend_bases import RendererBase
  File "/usr/local/lib/python3.6/dist-packages/matplotlib-2.0.2-py3.6-linux-x86_64.egg/matplotlib/backend_bases.py", line 63, in <module>
    import matplotlib.textpath as textpath
  File "/usr/local/lib/python3.6/dist-packages/matplotlib-2.0.2-py3.6-linux-x86_64.egg/matplotlib/textpath.py", line 20, in <module>
    from matplotlib.mathtext import MathTextParser
  File "/usr/local/lib/python3.6/dist-packages/matplotlib-2.0.2-py3.6-linux-x86_64.egg/matplotlib/mathtext.py", line 43, in <module>
    [int(x) for x in pyparsing.__version__.split('.')] < [2, 0, 0]):
  File "/usr/local/lib/python3.6/dist-packages/matplotlib-2.0.2-py3.6-linux-x86_64.egg/matplotlib/mathtext.py", line 43, in <listcomp>
    [int(x) for x in pyparsing.__version__.split('.')] < [2, 0, 0]):
ValueError: invalid literal for int() with base 10: '2a1'
```

Since I have no idea on how to move forward after this error, I am thankfull for every bit of help I can get.

**Comment by erogol** [comment]
It's a bug in matplotlib not TTS. Installing pyparsing 2.4.0 before matplotlib would solve it.
