### ISSUE TITLE
Suggestion: Text alphabet (characters)

### ISSUE THREAD

**Issue by Edresson** [mozilla/TTS#355]
Hello,

 I would like to suggest adding the Latin characters in the alphabet (util/text/symbols.py ). I believe it is very welcome to facilitate Transfer Learning between languages. Allowing for easier training in Portuguese and Spanhol for example.
Since :
`_characters = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz!\'(),-.:;? '
`
Would be:

`_characters='ABCDEFGHIJKLMNOPQRSTUVWXYZÇÃÀÁÂÊÉÍÓÔÕÚÛÑabcdefghijklmnopqrstuvwxyzçãàáâêéíóôõúûñ!\'(),-.:;?'`

Currently when I do transfer learning I am replacing capital letters with missing characters, however it is not a good practice.

**Comment by erogol** [comment]
txt for picking that up. However, I think it is very user-specific. Maybe it is better to define the character list in config.json to be more flexible but as you increase the list, your model is also getting larger quite considerably. Therefore it is not a good idea to provide a huge har list due to practical reasons

**Comment by thorstenMueller** [comment]
I'd agree suggestion by @erogol . Your additions might be good for portuguese but eg. german special chars would be missing (äüöß).
Adding specific chars for all global languages would end in a really long string of possible characters.

**Comment by Edresson** [comment]
@erogol  I agree with you !
I believe that replacing capital letters with missing letters is good enough for Transfer Learning, I tested it in Brazilian Portuguese and got good results.

To train a new model in another language and after adding it to this repository, do you suggest a fork and within that fork create a new branch with the necessary modifications?

I ask why we intend to provide a multi-speaker model for Brazilian Portuguese.

**Comment by erogol** [comment]
I think we can override the default charset if something is given in config.json. That would be a nice PR if it sounds good for you. Then, we don't really fork for every language but give the config file.

**Comment by Edresson** [comment]
@erogol  Do you recommend adding all Text parameters (characters, punctuation) and Phoneme parameters (_vowels, _non_pulmonic_consonants, _pulmonic_consonants, _suprasegmentals, _other_symbols, _diacrilics) to config.json?

**Comment by erogol** [comment]
I think if you give a list in config.json it should overwrite everything in symbols. So TTS should only use the list you give.

**Comment by Edresson** [comment]
@erogol  I submitted a pull request with the suggestion discussed here. I ran all the tests and everything seems to work fine.

**Comment by Edresson** [comment]
@erogol  I submitted a pull request with the suggestions discussed here for the dev branch as well.

I noticed a problem in the "dev" branch, the scripts are not saving all phonemes in phoneme_cache_path, so the execution is interrupted (this only happens in the "dev" branch, in the master branch everything works fine). The problem was already present before my commit.

**Comment by erogol** [comment]
@Edresson can you post the error message?

**Comment by Edresson** [comment]
@erogol   I am running on an anaconda env with Python 3.7.3

```> Using CUDA:  True
 > Number of GPUs:  1
 > Git Hash: c825b63
 > Experiment folder: ../datasets/Models/ljspeech-stft_params-March-02-2020_05+27PM-c825b63
 > Setting up Audio Processor...
 | > sample_rate:22050
 | > num_mels:80
 | > min_level_db:-100
 | > frame_shift_ms:None
 | > frame_length_ms:None
 | > ref_level_db:20
 | > num_freq:1025
 | > power:1.5
 | > preemphasis:0.98
 | > griffin_lim_iters:60
 | > signal_norm:True
 | > symmetric_norm:True
 | > mel_fmin:0
 | > mel_fmax:8000.0
 | > max_norm:4.0
 | > clip_norm:True
 | > do_trim_silence:True
 | > trim_db:60
 | > sound_norm:False
 | > hop_length:256
 | > win_length:1024
 | > n_fft:2048
 > Using model: Tacotron2
 | > Num output units : 1025

 > Model has 28915154 parameters
 > Number of outputs per iteration: 7

 > DataLoader initialization
 | > Use phonemes: True
   | > phoneme language: en-us
 | > Number of instances : 12969
 | > Max length sequence: 187
 | > Min length sequence: 5
 | > Avg length sequence: 98.3403500655409
 | > Num. instances discarded by max-min (max=150, min=6) seq limits: 627
 | > Batch group size: 0.

 > Epoch 0/1000
 ! Run is removed from ../datasets/Models/ljspeech-stft_params-March-02-2020_05+27PM-c825b63
Traceback (most recent call last):
  File "train.py", line 720, in <module>
    main(args)
  File "train.py", line 636, in main
    global_step, epoch)
  File "train.py", line 144, in train
    for num_iter, data in enumerate(data_loader):
  File "/home/edresson/anaconda3/envs/py373/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/home/edresson/anaconda3/envs/py373/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 856, in _next_data
    return self._process_data(data)
  File "/home/edresson/anaconda3/envs/py373/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 881, in _process_data
    data.reraise()
  File "/home/edresson/anaconda3/envs/py373/lib/python3.7/site-packages/torch/_utils.py", line 394, in reraise
    raise self.exc_type(msg)
IndexError: Caught IndexError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/edresson/anaconda3/envs/py373/lib/python3.7/site-packages/TTS-0.0.1+c825b63-py3.7.egg/TTS/datasets/TTSDataset.py", line 94, in _load_or_generate_phoneme_sequence
    phonemes = np.load(cache_path)
  File "/home/edresson/anaconda3/envs/py373/lib/python3.7/site-packages/numpy/lib/npyio.py", line 428, in load
    fid = open(os_fspath(file), "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'mozilla_us_phonemes_2_1/LJ017-0210_phoneme.npy'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/edresson/anaconda3/envs/py373/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/edresson/anaconda3/envs/py373/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/edresson/anaconda3/envs/py373/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/edresson/anaconda3/envs/py373/lib/python3.7/site-packages/TTS-0.0.1+c825b63-py3.7.egg/TTS/datasets/TTSDataset.py", line 164, in __getitem__
    return self.load_data(idx)
  File "/home/edresson/anaconda3/envs/py373/lib/python3.7/site-packages/TTS-0.0.1+c825b63-py3.7.egg/TTS/datasets/TTSDataset.py", line 113, in load_data
    text = self._load_or_generate_phoneme_sequence(wav_file, text)
  File "/home/edresson/anaconda3/envs/py373/lib/python3.7/site-packages/TTS-0.0.1+c825b63-py3.7.egg/TTS/datasets/TTSDataset.py", line 97, in _load_or_generate_phoneme_sequence
    cache_path)
  File "/home/edresson/anaconda3/envs/py373/lib/python3.7/site-packages/TTS-0.0.1+c825b63-py3.7.egg/TTS/datasets/TTSDataset.py", line 84, in _generate_and_cache_phoneme_sequence
    enable_eos_bos=False)
  File "/home/edresson/anaconda3/envs/py373/lib/python3.7/site-packages/TTS-0.0.1+c825b63-py3.7.egg/TTS/utils/text/__init__.py", line 68, in phoneme_to_sequence
    to_phonemes = text2phone(clean_text, language)
  File "/home/edresson/anaconda3/envs/py373/lib/python3.7/site-packages/TTS-0.0.1+c825b63-py3.7.egg/TTS/utils/text/__init__.py", line 47, in text2phone
    ph = phonemize(text, separator=seperator, strip=False, njobs=1, backend='espeak', language=language, preserve_punctuation=True)
  File "/home/edresson/anaconda3/envs/py373/lib/python3.7/site-packages/phonemizer/phonemize.py", line 172, in phonemize
    text, separator=separator, strip=strip, njobs=njobs)
  File "/home/edresson/anaconda3/envs/py373/lib/python3.7/site-packages/phonemizer/backend/base.py", line 126, in phonemize
    text = self._punctuator.restore(text, punctuation_marks)
  File "/home/edresson/anaconda3/envs/py373/lib/python3.7/site-packages/phonemizer/punctuation.py", line 146, in restore
    return cls._restore_aux(str2list(text), marks, 0)
  File "/home/edresson/anaconda3/envs/py373/lib/python3.7/site-packages/phonemizer/punctuation.py", line 166, in _restore_aux
    [text[0] + m.mark + text[1]] + text[2:], marks[1:], n)
IndexError: list index out of range

```

pip freeze 

```
absl-py==0.9.0
attrdict==2.0.1
attrs==19.3.0
audioread==2.1.8
bokeh==1.4.0
cachetools==4.0.0
certifi==2019.11.28
cffi==1.14.0
chardet==3.0.4
Click==7.0
clldutils==3.5.0
colorlog==4.1.0
csvw==1.7.0
cycler==0.10.0
decorator==4.4.2
Flask==1.1.1
google-auth==1.11.2
google-auth-oauthlib==0.4.1
grpcio==1.27.2
idna==2.9
isodate==0.6.0
itsdangerous==1.1.0
Jinja2==2.11.1
joblib==0.14.1
kiwisolver==1.1.0
librosa==0.7.2
llvmlite==0.31.0
Markdown==3.2.1
MarkupSafe==1.1.1
matplotlib==3.1.3
numba==0.48.0
numpy==1.18.1
oauthlib==3.1.0
packaging==20.1
phonemizer==2.1
Pillow==7.0.0
protobuf==3.11.3
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycparser==2.19
pyparsing==2.4.6
python-dateutil==2.8.1
PyYAML==5.3
regex==2020.2.20
requests==2.23.0
requests-oauthlib==1.3.0
resampy==0.2.2
rfc3986==1.3.2
rsa==4.0
scikit-learn==0.22.2
scipy==1.4.1
segments==2.1.3
six==1.14.0
SoundFile==0.10.3.post1
tabulate==0.8.6
tensorboard==2.1.0
tensorboardX==2.0
torch==1.4.0
tornado==6.0.3
tqdm==4.43.0
TTS==0.0.1+c825b63
Unidecode==1.1.1
uritemplate==3.0.1
urllib3==1.25.8
Werkzeug==1.0.0
```
I've already created a new env and installed the requirements of the dev branch, but that didn't solve the problem.

**Comment by erogol** [comment]
thats ```phonemizer``` bug. If you install it from the latest master branch it should work.

**Comment by Edresson** [comment]
@erogol  Thank you very much, everything is working fine now :)
