### ISSUE TITLE
NameError: name 'mode' is not defined

### ISSUE THREAD

**Issue by hamzology** [mozilla/TTS#37]
Hi,
When I am running the benchmark with checkpoint_272976.pth.tar I am getting this error:

`` | > Number of characters : 149
Traceback (most recent call last):
  File "ttsbechmark.py", line 46, in <module>
    model = Tacotron(CONFIG.embedding_size, CONFIG.num_freq, CONFIG.num_mels, CONFIG.r)
  File "/media/hamza/Local Disk/Projects/Untitled Folder/TTS/models/tacotron.py", line 20, in __init__
    self.decoder = Decoder(256, mel_dim, r)
  File "/media/hamza/Local Disk/Projects/Untitled Folder/TTS/layers/tacotron.py", line 203, in __init__
    self.mode = mode
NameError: name 'mode' is not defined

Thanks

**Comment by erogol** [comment]
You need to update you local copy with the latest master branch.
