### ISSUE TITLE
Cannot start training on LibriTTS when enabling phonemizer 

### ISSUE THREAD

**Issue by george-roussos** [mozilla/TTS#374]
If I disable the phonemizer, training starts okay, but I enable it, I get an error that one of the .npy files weren't found: 

````
Traceback (most recent call last):
  File "train.py", line 715, in <module>
    main(args)
  File "train.py", line 631, in main
    global_step, epoch)
  File "train.py", line 144, in train
    for num_iter, data in enumerate(data_loader):
  File "/home/georgios_roussos/.local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/home/georgios_roussos/.local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 856, in _next_data
    return self._process_data(data)
  File "/home/georgios_roussos/.local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 881, in _process_data
    data.reraise()
  File "/home/georgios_roussos/.local/lib/python3.6/site-packages/torch/_utils.py", line 394, in reraise
    raise self.exc_type(msg)
IndexError: Caught IndexError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/georgios_roussos/TTS_m/tts_namespace/TTS/datasets/TTSDataset.py", line 94, in _load_or_generate_phoneme_sequence
    phonemes = np.load(cache_path)
  File "/home/georgios_roussos/.local/lib/python3.6/site-packages/numpy/lib/npyio.py", line 428, in load
    fid = open(os_fspath(file), "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/mozilla_us_phonemes_2_1/5339_14134_000072_000000_phoneme.npy'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/georgios_roussos/.local/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/georgios_roussos/.local/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/georgios_roussos/.local/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/georgios_roussos/TTS_m/tts_namespace/TTS/datasets/TTSDataset.py", line 164, in __getitem__
    return self.load_data(idx)
  File "/home/georgios_roussos/TTS_m/tts_namespace/TTS/datasets/TTSDataset.py", line 113, in load_data
    text = self._load_or_generate_phoneme_sequence(wav_file, text)
  File "/home/georgios_roussos/TTS_m/tts_namespace/TTS/datasets/TTSDataset.py", line 97, in _load_or_generate_phoneme_sequence
    cache_path)
  File "/home/georgios_roussos/TTS_m/tts_namespace/TTS/datasets/TTSDataset.py", line 84, in _generate_and_cache_phoneme_sequence
    enable_eos_bos=False)
  File "/home/georgios_roussos/TTS_m/tts_namespace/TTS/utils/text/__init__.py", line 68, in phoneme_to_sequence
    to_phonemes = text2phone(clean_text, language)
  File "/home/georgios_roussos/TTS_m/tts_namespace/TTS/utils/text/__init__.py", line 47, in text2phone
    ph = phonemize(text, separator=seperator, strip=False, njobs=1, backend='espeak', language=language, preserve_punctuation=True)
  File "/usr/local/lib/python3.6/dist-packages/phonemizer/phonemize.py", line 172, in phonemize
    text, separator=separator, strip=strip, njobs=njobs)
  File "/usr/local/lib/python3.6/dist-packages/phonemizer/backend/base.py", line 126, in phonemize
    text = self._punctuator.restore(text, punctuation_marks)
  File "/usr/local/lib/python3.6/dist-packages/phonemizer/punctuation.py", line 146, in restore
    return cls._restore_aux(str2list(text), marks, 0)
  File "/usr/local/lib/python3.6/dist-packages/phonemizer/punctuation.py", line 166, in _restore_aux
    [text[0] + m.mark + text[1]] + text[2:], marks[1:], n)
IndexError: list index out of range

Traceback (most recent call last):
  File "train.py", line 715, in <module>
    main(args)
  File "train.py", line 631, in main
    global_step, epoch)
  File "train.py", line 144, in train
    for num_iter, data in enumerate(data_loader):
  File "/home/georgios_roussos/.local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/home/georgios_roussos/.local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 856, in _next_data
    return self._process_data(data)
  File "/home/georgios_roussos/.local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 881, in _process_data
    data.reraise()
  File "/home/georgios_roussos/.local/lib/python3.6/site-packages/torch/_utils.py", line 394, in reraise
    raise self.exc_type(msg)
IndexError: Caught IndexError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/georgios_roussos/TTS_m/tts_namespace/TTS/datasets/TTSDataset.py", line 94, in _load_or_generate_phoneme_sequence
    phonemes = np.load(cache_path)
  File "/home/georgios_roussos/.local/lib/python3.6/site-packages/numpy/lib/npyio.py", line 428, in load
    fid = open(os_fspath(file), "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/mozilla_us_phonemes_2_1/5339_14134_000072_000000_phoneme.npy'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/georgios_roussos/.local/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/georgios_roussos/.local/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/georgios_roussos/.local/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/georgios_roussos/TTS_m/tts_namespace/TTS/datasets/TTSDataset.py", line 164, in __getitem__
    return self.load_data(idx)
  File "/home/georgios_roussos/TTS_m/tts_namespace/TTS/datasets/TTSDataset.py", line 113, in load_data
    text = self._load_or_generate_phoneme_sequence(wav_file, text)
  File "/home/georgios_roussos/TTS_m/tts_namespace/TTS/datasets/TTSDataset.py", line 97, in _load_or_generate_phoneme_sequence
    cache_path)
  File "/home/georgios_roussos/TTS_m/tts_namespace/TTS/datasets/TTSDataset.py", line 84, in _generate_and_cache_phoneme_sequence
    enable_eos_bos=False)
  File "/home/georgios_roussos/TTS_m/tts_namespace/TTS/utils/text/__init__.py", line 68, in phoneme_to_sequence
    to_phonemes = text2phone(clean_text, language)
  File "/home/georgios_roussos/TTS_m/tts_namespace/TTS/utils/text/__init__.py", line 47, in text2phone
    ph = phonemize(text, separator=seperator, strip=False, njobs=1, backend='espeak', language=language, preserve_punctuation=True)
  File "/usr/local/lib/python3.6/dist-packages/phonemizer/phonemize.py", line 172, in phonemize
    text, separator=separator, strip=strip, njobs=njobs)
  File "/usr/local/lib/python3.6/dist-packages/phonemizer/backend/base.py", line 126, in phonemize
    text = self._punctuator.restore(text, punctuation_marks)
  File "/usr/local/lib/python3.6/dist-packages/phonemizer/punctuation.py", line 146, in restore
    return cls._restore_aux(str2list(text), marks, 0)
  File "/usr/local/lib/python3.6/dist-packages/phonemizer/punctuation.py", line 166, in _restore_aux
    [text[0] + m.mark + text[1]] + text[2:], marks[1:], n)
IndexError: list index out of range
````

I don't really wanna train without the phonemizer. Is there any reason why this is showing up? It goes away when I disable use of phonemes in the config file.

**Comment by domcross** [comment]
` FileNotFoundError: [Errno 2] No such file or directory: '/mozilla_us_phonemes_2_1/5339_14134_000072_000000_phoneme.npy' `

Is the path `/mozilla_us_phonemes_2_1/` correct (probably you meant `mozilla_us_phonemes_2_1` without leading `/`?) and is user running `train.py` allowed to write/read it?

**Comment by george-roussos** [comment]
Yes. I tried without the leading and chown on the dir. Other npy files are written in it.

**Comment by erogol** [comment]
Update your phonemizer module. Or install it from github.
