### ISSUE TITLE
AttributeError: 'AttrDict' object has no attribute 'attention_type' OSX

### ISSUE THREAD

**Issue by varungujjar** [mozilla/TTS#387]
Hi hope to gets some help here.. been sweating on this since last 3 days still cant get to work

Am building the server whl file using the following platform
OS: OSX
Python version 3.7.1
Model Tacotron2-iter-260K
builds fine

Other Perfectly Running model servers : Tacotron 2 + Forward Attention + PWGAN

while running the model server 'Tacotron2-iter-260K'i get the following error
is there anything wrong that am doing ?

would be great if someone could help me here.. :(

python -m TTS.server.server
> Loading TTS model ...
 | > model config:  /Volumes/Work/dev/text_to_speech/tts_env/lib/python3.7/site-packages/TTS/server/model/tts/config.json
 | > checkpoint file:  /Volumes/Work/dev/text_to_speech/tts_env/lib/python3.7/site-packages/TTS/server/model/tts/checkpoint.pth.tar
 > Setting up Audio Processor...
 | > sample_rate:22050
 | > num_mels:80
 | > min_level_db:-100
 | > frame_shift_ms:12.5
 | > frame_length_ms:50
 | > ref_level_db:20
 | > num_freq:1025
 | > power:1.5
 | > preemphasis:0.98
 | > griffin_lim_iters:60
 | > signal_norm:True
 | > symmetric_norm:False
 | > mel_fmin:0
 | > mel_fmax:8000.0
 | > max_norm:1.0
 | > clip_norm:True
 | > do_trim_silence:True
 | > trim_db:60
 | > sound_norm:False
 | > n_fft:2048
 | > hop_length:275
 | > win_length:1100
 > Using model: Tacotron2
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Volumes/Work/dev/homie/text_to_speech/tts_env/lib/python3.7/site-packages/TTS/server/server.py", line 62, in <module>
    synthesizer = Synthesizer(args)
  File "/Volumes/Work/dev/homie/text_to_speech/tts_env/lib/python3.7/site-packages/TTS/server/synthesizer.py", line 35, in __init__
    self.config.use_cuda)
  File "/Volumes/Work/dev/homie/text_to_speech/tts_env/lib/python3.7/site-packages/TTS/server/synthesizer.py", line 68, in load_tts
    self.tts_model = setup_model(self.input_size, num_speakers=num_speakers, c=self.tts_config)
  File "/Volumes/Work/dev/homie/text_to_speech/tts_env/lib/python3.7/site-packages/TTS/utils/generic_utils.py", line 311, in setup_model
    attn_type=c.attention_type,
AttributeError: 'AttrDict' object has no attribute 'attention_type'

**Comment by erogol** [comment]
that means you don'y have attention_type in config file. Check the default config.json and fill the missing fields in yours.
