### ISSUE TITLE
AssertionError: 22050 vs 48000

### ISSUE THREAD

**Issue by mwx2006** [mozilla/TTS#390]
Traceback (most recent call last):
  File "train.py", line 724, in <module>
    main(args)
  File "train.py", line 638, in main
    train_loss, global_step = train(model, criterion, criterion_st,
  File "train.py", line 145, in train
    for num_iter, data in enumerate(data_loader):
  File "C:\Users\MWX\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\utils\data\dataloader.py", line 345, in __next__
    data = self._next_data()
  File "C:\Users\MWX\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\utils\data\dataloader.py", line 856, in _next_data
    return self._process_data(data)
  File "C:\Users\MWX\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\utils\data\dataloader.py", line 881, in _process_data
    data.reraise()
  File "C:\Users\MWX\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\_utils.py", line 394, in reraise
    raise self.exc_type(msg)
AssertionError: Caught AssertionError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "C:\Users\MWX\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\utils\data\_utils\worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "C:\Users\MWX\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\MWX\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "D:\TTS\datasets\TTSDataset.py", line 166, in __getitem__
    return self.load_data(idx)
  File "D:\TTS\datasets\TTSDataset.py", line 112, in load_data
    wav = np.asarray(self.load_wav(wav_file), dtype=np.float32)
  File "D:\TTS\datasets\TTSDataset.py", line 70, in load_wav
    audio = self.ap.load_wav(filename)
  File "D:\TTS\utils\audio.py", line 257, in load_wav
    assert self.sample_rate == sr, "%s vs %s"%(self.sample_rate, sr)
AssertionError: 22050 vs 48000

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 732, in <module>
    remove_experiment_folder(OUT_PATH)
  File "D:\TTS\utils\generic_utils.py", line 80, in remove_experiment_folder
    shutil.rmtree(experiment_path)
  File "C:\Users\MWX\AppData\Local\Programs\Python\Python38\lib\shutil.py", line 737, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\Users\MWX\AppData\Local\Programs\Python\Python38\lib\shutil.py", line 615, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "C:\Users\MWX\AppData\Local\Programs\Python\Python38\lib\shutil.py", line 613, in _rmtree_unsafe
    os.unlink(fullname)
PermissionError: [WinError 32] 另一个程序正在使用此文件，进程无法访问。: 'd:\\TTS\\data\\allmj\\out\\ljspeech-stft_params-April-06-2020_03+10PM-fab74dd\\events.out.tfevents.1586157056.DESK
TOP-DJ92M16'

**Comment by erogol** [comment]
you need to set the sampling rate right in config.json or resample your dataset to 22050.

**Comment by souvikg544** [comment]
I have the same error ... Can you please explain how do I sampling rate in config.json ... Also I have been using  - https://colab.research.google.com/drive/1F8mdG6Vm7kAigyLZhc37_vTQBnh7wgk2?usp=sharing  

In the above notebook I have been trying with a custom dataset built by me . All the cells work except while I am doing trainer.fit() . Can you tell me where do I put the sample_rate as a parameter

**Comment by devdevgoat** [comment]
Had the same error trying to train a model using coqui's python notebooks. @erogol is correct, you have to tell the audio processor what the sample rate is. For Croqui, the config I was using inherited the audio processor class so I just manually set the attribute AFTER initilization:

```python
from TTS.tts.configs.glow_tts_config import GlowTTSConfig
config = GlowTTSConfig(
    batch_size=32,
    eval_batch_size=16,
    num_loader_workers=4,
    num_eval_loader_workers=4,
    run_eval=True,
    test_delay_epochs=-1,
    epochs=100,
    text_cleaner="phoneme_cleaners",
    use_phonemes=True,
    phoneme_language="en-us",
    phoneme_cache_path=os.path.join(output_path, "phoneme_cache"),
    print_step=25,
    print_eval=False,
    mixed_precision=True,
    output_path=output_path,
    datasets=[dataset_config],
    save_step=1000,
    eval_split_size = 0.07142857142857142
)

config.audio.sample_rate=48000
```

Just set the rate equal to whatever the assertion error spits out as the mismatch.

Additionally, you might also run into an error about shape, it's because the .wav file is stereo, but you need to convert to mono. I used the [following guide to bulk convert a batch of files out in mono format](https://www.reddit.com/r/filtersweep/comments/fxedtq/fyi_ways_to_batch_convert_samples_from_stereo_to/).

**Comment by Lonas13** [comment]
> Additionally, you might also run into an error about shape, it's because the .wav file is stereo, but you need to convert to mono. I used the [following guide to bulk convert a batch of files out in mono format](https://www.reddit.com/r/filtersweep/comments/fxedtq/fyi_ways_to_batch_convert_samples_from_stereo_to/).

THANK YOU SO MUCH! I've been struggling a lot getting things up and running and would not have known where to go next were it not for you mentioning this as an aside. 

Additionally, you can use the "pydub" python module to batch convert as well. I asked chatGPT to write a script using pydub and that worked for me too.
