### ISSUE TITLE
Where to find metadata_val.csv

### ISSUE THREAD

**Issue by mkagenius** [mozilla/TTS#41]
I downloaded the dataset from https://keithito.com/LJ-Speech-Dataset/  by click on Download button. Assuming it to be enough I ran `python train.py --config_path config.json` by modifying the config file according to my own computer. 

First it complained about missing `metadata_train.csv` and then about missing `metadata_val.csv` . 

In the readme, there is no mention whether I need to run anything else to do preprocessing. So maybe something I am missing. 

To try to fix, I copied metadata.csv into `metadata_train.csv` and `metadata_val.csv`  files and gave it a run and got following error:

```
 > Git Hash: 186a81c
 > Experiment folder: /Users/manish/Work/TTS/experiments/July-11-2018_04:51PM-best-model-186a81c
 > Reading LJSpeech from - /Users/manish/Downloads/LJSpeech-1.1/wavs
 | > Number of instances : 13100
 | > Max length sequence 187
 | > Min length sequence 5
 | > Avg length sequence 98.34648854961831
 | > 0 instances are ignored by min_seq_len (0)
 > Reading LJSpeech from - /Users/manish/Downloads/LJSpeech-1.1/wavs
 | > Number of instances : 13100
 | > Max length sequence 187
 | > Min length sequence 5
 | > Avg length sequence 98.34648854961831
 | > 0 instances are ignored by min_seq_len (0)
 | > Number of characters : 149

 > Starting a new training
 | > Model has 7385090 parameters
 | > Epoch 0/1000
 ! Run is removed from /Users/manish/Work/TTS/experiments/July-11-2018_04:51PM-best-model-186a81c
Traceback (most recent call last):
  File "train.py", line 434, in <module>
    main(args)
  File "train.py", line 424, in main
    model, criterion, criterion_st, train_loader, optimizer, optimizer_st, epoch)
  File "train.py", line 112, in train
    model.forward(text_input, mel_input)
  File "/Users/manish/Work/TTS/models/tacotron.py", line 31, in forward
    encoder_outputs, mel_specs)
  File "/Users/manish/miniconda3/envs/tts/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/Users/manish/Work/TTS/layers/tacotron.py", line 242, in forward
    memory = memory.view(B, memory.size(1) // self.r, -1)
RuntimeError: invalid argument 2: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Call .contiguous() before .view(). at /Users/soumith/minicondabuild3/conda-bld/pytorch_1524590658547/work/aten/src/TH/generic/THTensor.cpp:280

```

**Comment by mkagenius** [comment]
So, I fixed the issues by:

* copying metadata.csv into two files as stated above.
* Call .contiguous() before .view() , line 242 of tacotron.py
* Change model.module to just model

I dont know if it really worked or not but I left it running for 10 mins and there was no error. My mac is only CPU based so 0/1000 epochs tested in those 10 minutes.

**Comment by erogol** [comment]
Now I updated the README. https://github.com/mozilla/TTS#training-and-finetunning
