### ISSUE TITLE
librosa, numba.decorators dependency

### ISSUE THREAD

**Issue by xeb** [mozilla/TTS#437]
I keep running into an issue (in Docker and with virtualenv) where librosa==0.6.2

```
root@ed2a55775478:/pwd# python TTS/train.py --config_path config.json 
Traceback (most recent call last):
  File "TTS/train.py", line 16, in <module>
    from TTS.utils.audio import AudioProcessor
  File "/opt/conda/lib/python3.6/site-packages/TTS-0.0.3-py3.6.egg/TTS/utils/audio.py", line 1, in <module>
    import librosa
  File "/opt/conda/lib/python3.6/site-packages/librosa/__init__.py", line 12, in <module>
    from . import core
  File "/opt/conda/lib/python3.6/site-packages/librosa/core/__init__.py", line 125, in <module>
    from .time_frequency import *  # pylint: disable=wildcard-import
  File "/opt/conda/lib/python3.6/site-packages/librosa/core/time_frequency.py", line 11, in <module>
    from ..util.exceptions import ParameterError
  File "/opt/conda/lib/python3.6/site-packages/librosa/util/__init__.py", line 77, in <module>
    from .utils import *  # pylint: disable=wildcard-import
  File "/opt/conda/lib/python3.6/site-packages/librosa/util/utils.py", line 15, in <module>
    from .decorators import deprecated
  File "/opt/conda/lib/python3.6/site-packages/librosa/util/decorators.py", line 9, in <module>
    from numba.decorators import jit as optional_jit
ModuleNotFoundError: No module named 'numba.decorators'
```

And here's the output of `pip freeze`:
```
$ pip freeze
attrdict==2.0.1
attrs==19.3.0
audioread==2.1.8
bokeh==1.4.0
cffi==1.14.0
click==7.1.2
clldutils==3.5.2
colorlog==4.1.0
csvw==1.7.0
cycler==0.10.0
decorator==4.4.2
Flask==1.1.2
future==0.18.2
isodate==0.6.0
itsdangerous==2.0.0a1
Jinja2==3.0.0a1
joblib==0.15.1
kiwisolver==1.2.0
librosa==0.6.2
llvmlite==0.33.0
MarkupSafe==2.0.0a1
matplotlib==3.3.0rc1
numba==0.50.0
numpy==1.19.0rc2
packaging==20.4
phonemizer==2.2
Pillow==7.1.2
protobuf==3.12.2
pycparser==2.20
pyparsing==3.0.0a1
python-dateutil==2.8.1
PyYAML==5.3.1
regex==2020.6.8
resampy==0.2.2
rfc3986==1.4.0
scikit-learn==0.23.1
scipy==1.5.0rc2
segments==2.1.3
six==1.15.0
SoundFile==0.10.3.post1
tabulate==0.8.7
tensorboardX==2.0
threadpoolctl==2.1.0
torch==1.5.1
tornado==6.0.4
tqdm==4.46.1
-e git+https://github.com/mozilla/TTS.git@669776ae856c1f38be14b35ebc7504a3b5310119#egg=TTS
Unidecode==0.4.20
uritemplate==3.0.1
Werkzeug==1.0.1
```

Numba seems to have moved to the `numba.core.decorators` namespace in 0.50.0 -- since librosa is locked on 0.6.2, should the same be set (in setup.py) for numba 0.48.0?

If I add `numba==0.48.0` to setup.py -- this fixes things. (I'll just submit a PR...)

**Comment by erogol** [comment]
It is a librosa bug. It needs to be fixed on their side. Try installing the previous version of librosa.
