### ISSUE TITLE
KeyError: ((1, 1, 1000), '|u1') && tensorboradX error

### ISSUE THREAD

**Issue by Jackiexiao** [mozilla/TTS#46]
```
Traceback (most recent call last):
  File "/home/jackie/anaconda3/envs/tts/lib/python3.6/site-packages/PIL/Image.py", line 2460, in fromarray
    mode, rawmode = _fromarray_typemap[typekey]
KeyError: ((1, 1, 1000), '|u1')

During handling of the above exception, another exception occurred:


Traceback (most recent call last):
  File "train.py", line 477, in <module>
    main(args)
  File "train.py", line 468, in main
    val_loss = evaluate(model, criterion, criterion_st, val_loader, current_step)
  File "train.py", line 310, in evaluate
    tb.add_image('ValVisual/Reconstruction', const_spec, current_step)
  File "/home/jackie/anaconda3/envs/tts/lib/python3.6/site-packages/tensorboardX/writer.py", line 412, in add_image
    self.file_writer.add_summary(image(tag, img_tensor), global_step, walltime)
  File "/home/jackie/anaconda3/envs/tts/lib/python3.6/site-packages/tensorboardX/summary.py", line 205, in image
    image = make_image(tensor, rescale=rescale)
  File "/home/jackie/anaconda3/envs/tts/lib/python3.6/site-packages/tensorboardX/summary.py", line 243, in make_image
    image = Image.fromarray(tensor)
  File "/home/jackie/anaconda3/envs/tts/lib/python3.6/site-packages/PIL/Image.py", line 2463, in fromarray
    raise TypeError("Cannot handle this data type")
TypeError: Cannot handle this data type
```
Thx in advance!

**Comment by nicolasugrinovic** [comment]
I have the same error here. 

> Traceback (most recent call last):
  File "/home/nugrinovic/miniconda3/envs/mesh_funcspace/lib/python3.6/site-packages/PIL/Image.py", line 2490, in fromarray
    mode, rawmode = _fromarray_typemap[typekey]
KeyError: ((1, 1, 896), '|u1')
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/nugrinovic/.local/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3296, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-de14ea1cfd01>", line 1, in <module>
    self._writer_full.add_image(sum_name, image_numpy, it)
  File "/home/nugrinovic/miniconda3/envs/mesh_funcspace/lib/python3.6/site-packages/tensorboardX/writer.py", line 412, in add_image
    self.file_writer.add_summary(image(tag, img_tensor), global_step, walltime)
  File "/home/nugrinovic/miniconda3/envs/mesh_funcspace/lib/python3.6/site-packages/tensorboardX/summary.py", line 205, in image
    image = make_image(tensor, rescale=rescale)
  File "/home/nugrinovic/miniconda3/envs/mesh_funcspace/lib/python3.6/site-packages/tensorboardX/summary.py", line 243, in make_image
    image = Image.fromarray(tensor)
  File "/home/nugrinovic/miniconda3/envs/mesh_funcspace/lib/python3.6/site-packages/PIL/Image.py", line 2492, in fromarray
    raise TypeError("Cannot handle this data type")
TypeError: Cannot handle this data type
