### ISSUE TITLE
RuntimeError: DataLoader worker (pid 3069) is killed by signal: Killed.

### ISSUE THREAD

**Issue by andrenatal** [mozilla/TTS#460]
I'm getting the following error mid-training when using LJ Speech Dataset on a GTX 1070 with PyTorch 1.5.1 and python 3.6.9 on Ubuntu 18.

```
....
   --> STEP: 309/390 -- GLOBAL_STEP: 91150
     | > decoder_loss: 0.20866  (0.19815)
     | > postnet_loss: 0.17622  (0.16908)
     | > stopnet_loss: 0.01802  (0.02207)
     | > ga_loss: 0.00028  (0.00108)
     | > loss: 0.38516
     | > align_error: 0.43465  (0.49214)
     | > avg_spec_len: 723.90625
     | > avg_text_len: 128.71875
     | > step_time: 3.02
     | > loader_time: 0.01
     | > lr: 0.00010

   --> STEP: 334/390 -- GLOBAL_STEP: 91175
     | > decoder_loss: 0.20624  (0.19872)
     | > postnet_loss: 0.17365  (0.16941)
     | > stopnet_loss: 0.02025  (0.02168)
     | > ga_loss: 0.00038  (0.00102)
     | > loss: 0.38027
     | > align_error: 0.43522  (0.48506)
     | > avg_spec_len: 750.15625
     | > avg_text_len: 134.46875
     | > step_time: 1.67
     | > loader_time: 0.01
     | > lr: 0.00010
 ! Run is kept in /home/andre/projects/tts-output/ljspeech-July-08-2020_11+18AM-3366328
Traceback (most recent call last):
  File "train.py", line 676, in <module>
    main(args)
  File "train.py", line 591, in main
    global_step, epoch)
  File "train.py", line 170, in train
    text_input, text_lengths, mel_input, speaker_ids=speaker_ids)
  File "/home/andre/projects/TTS/venv/lib/python3.6/site-packages/torch-1.5.1-py3.6-linux-x86_64.egg/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/andre/projects/TTS/venv/lib/python3.6/site-packages/TTS-0.0.3+3366328-py3.6.egg/TTS/models/tacotron2.py", line 75, in forward
    encoder_outputs, mel_specs, mask)
  File "/home/andre/projects/TTS/venv/lib/python3.6/site-packages/torch-1.5.1-py3.6-linux-x86_64.egg/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/andre/projects/TTS/venv/lib/python3.6/site-packages/TTS-0.0.3+3366328-py3.6.egg/TTS/layers/tacotron2.py", line 264, in forward
    decoder_output, attention_weights, stop_token = self.decode(memory)
  File "/home/andre/projects/TTS/venv/lib/python3.6/site-packages/TTS-0.0.3+3366328-py3.6.egg/TTS/layers/tacotron2.py", line 218, in decode
    query_input, (self.query, self.attention_rnn_cell_state))
  File "/home/andre/projects/TTS/venv/lib/python3.6/site-packages/torch-1.5.1-py3.6-linux-x86_64.egg/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/andre/projects/TTS/venv/lib/python3.6/site-packages/torch-1.5.1-py3.6-linux-x86_64.egg/torch/nn/modules/rnn.py", line 955, in forward
    self.bias_ih, self.bias_hh,
  File "/home/andre/projects/TTS/venv/lib/python3.6/site-packages/torch-1.5.1-py3.6-linux-x86_64.egg/torch/utils/data/_utils/signal_handling.py", line 66, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 3069) is killed by signal: Killed.
```

**Comment by erogol** [comment]
it might be "out of memory".

**Comment by andrenatal** [comment]
I'm also having this issue when running on a different server, dedicated to the TTS training. 

```


    EPOCH: 480/1000

    Number of output frames: 5

    TRAINING (2020-07-22 21:59:20)

--> STEP: 4/53 -- GLOBAL_STEP: 25925
| > decoder_loss: 0.12594 (0.11075)
| > postnet_loss: 0.10912 (0.09601)
| > stopnet_loss: 0.04531 (0.10720)
| > ga_loss: 0.00919 (0.01194)
| > loss: 0.24424
| > align_error: 0.40299 (0.40881)
| > avg_spec_len: 279.0
| > avg_text_len: 36.453125
| > step_time: 2.75
| > loader_time: 0.03
| > lr: 0.00010

--> STEP: 29/53 -- GLOBAL_STEP: 25950
| > decoder_loss: 0.14363 (0.13465)
| > postnet_loss: 0.12181 (0.11508)
| > stopnet_loss: 0.05399 (0.07072)
| > ga_loss: 0.00060 (0.00314)
| > loss: 0.26604
| > align_error: 0.38774 (0.38671)
| > avg_spec_len: 678.921875
| > avg_text_len: 99.953125
| > step_time: 2.03
| > loader_time: 0.02
| > lr: 0.00010
! Run is kept in /home/andre/projects/tts-mozilla/perola/output_model/perola-July-22-2020_12+10AM-599c2db
Traceback (most recent call last):
File "train.py", line 676, in <module>
main(args)
File "train.py", line 591, in main
global_step, epoch)
File "train.py", line 191, in train
loss_dict['loss'].backward()
File "/home/andre/projects/tts-mozilla/tts_env/lib/python3.6/site-packages/torch-1.5.1-py3.6-linux-x86_64.egg/torch/tensor.py", line 198, in backward
torch.autograd.backward(self, gradient, retain_graph, create_graph)
File "/home/andre/projects/tts-mozilla/tts_env/lib/python3.6/site-packages/torch-1.5.1-py3.6-linux-x86_64.egg/torch/autograd/init.py", line 100, in backward
allow_unreachable=True) # allow_unreachable flag
File "/home/andre/projects/tts-mozilla/tts_env/lib/python3.6/site-packages/torch-1.5.1-py3.6-linux-x86_64.egg/torch/utils/data/_utils/signal_handling.py", line 66, in handler
_error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 596) is killed by signal: Killed.

```

**Comment by erogol** [comment]
What is your batch size? 32 ?

**Comment by andrenatal** [comment]
> What is your batch size? 32 ?
> 

Yes.

```
    // TRAINING
    "batch_size": 32,       // Batch size for training. Lower values than 32 might cause hard to learn attention. It is overwritten by 'gradual_training'.
    "eval_batch_size":16,
```

> Are you running on docker?
> 

No.

> Can you run the same code with `num_loader_workers=0` in config.json? It should give a better error message.
> 
> It might also be a PyTorch issue [pytorch/pytorch#8976](https://github.com/pytorch/pytorch/issues/8976)

Ok

**Comment by dan-wells** [comment]
I had a similar problem, training killed by OOM Killer after some time, somewhere after 20k steps. That was on a desktop with 16GB memory, then I observed directly the memory consumption increase over time after continuing training on a server with 256GB (which was plenty!).

Early in the training, I saw a warning from matplotlib:
`/home/s1462938/tools/mozilla-tts/tts_namespace/TTS/utils/visual.py:14: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface ('matplotlib.pyplot.figure') are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam 'figure.max_open_warning').`

I added some `plt.close()` calls in the functions generating alignment and spectrogram plots and it seems to have solved the issue -- see https://github.com/dan-wells/mozilla-tts/commit/3136204456f10a8aeae572549cc4880d652ace9a. At least with this I see no memory consumption increase over the first 10k steps of a training run using the same config as before, with `num_loader_workers=4` and `num_val_loader_workers=4`.

This doesn't affect the visibility of those plots in TensorBoard, but I haven't tested the notebook which calls `TTS.utils.visual.visualize` (which I changed as well just for consistency, but I guess it's less likely to eat a ton of memory than something running throughout training iterations).

@andrenatal Do you maybe see a similar warning pyplot memory consumption?

**Comment by andrenatal** [comment]
Thanks @dan-wells. 

Reducing `num_loader_workers` to `0` didn't work.

I'll try applying your patch.

Thanks for pointing that out!

**Comment by nmstoker** [comment]
Thanks @dan-wells - this worked for me with the Vocoder where I was also experiencing a memory issue. I'd actually tried something similar myself but had applied the close at the wrong point so it wasn't working. Your code did the trick.

The location of visual.py moved after the refactor in dev but the exact same changes within the file work.

**Comment by dan-wells** [comment]
@nmstoker I saw your Discourse thread about the vocoder training and wondered if it was the same thing. Glad to hear it helps there too!

**Comment by erogol** [comment]
I added the close statements in dev branch. Pls reopen if you see the same problem again using dev branch.
