### ISSUE TITLE
Runtime exception due to scipy.io.wavfile import  problem 

### ISSUE THREAD

**Issue by jyegerlehner** [mozilla/TTS#477]
In both the master and dev branches (as of a few days ago) I see the following failure running the test_audio.py nosetests:

```
(tts) ll-Series:~/dev/models/tensorflow/TTS$ nosetests tests/test_audio.py 
E.....
======================================================================
ERROR: 1. load wav
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jim/dev/models/tensorflow/TTS/tests/test_audio.py", line 44, in test_audio_synthesis
    _test(1., False, False, False)
  File "/home/jim/dev/models/tensorflow/TTS/tests/test_audio.py", line 41, in _test
    self.ap.save_wav(wav_, OUT_PATH + file_name)
  File "/home/jim/dev/models/tensorflow/TTS/utils/audio.py", line 322, in save_wav
    scipy.io.wavfile.write(path, self.sample_rate, wav_norm.astype(np.int16))
AttributeError: module 'scipy.io' has no attribute 'wavfile'
-------------------- >> begin captured stdout << ---------------------
 > Sanity check for the process wav -> mel -> wav
 | > Creating wav file at :  /audio_test-melspec_max_norm_1.0-signal_norm_False-symmetric_False-clip_norm_False.wav

--------------------- >> end captured stdout << ----------------------

----------------------------------------------------------------------
Ran 6 tests in 0.450s

FAILED (errors=1)

```
I also saw this exception being thrown running train.py in master when it gets to the eval stage and tried to write out the wav files.

I'm running on ubuntu 18.04 and python 3.8.3. I'm guessing this is a recent change in behavior of python imports, if this hasn't been a problem till now.

I have a couple candidate PRs to fix this in master and dev; will submit.

**Comment by erogol** [comment]
what is your scipy version?

**Comment by erogol** [comment]
this is fixed with your PR thx.

**Comment by jyegerlehner** [comment]
I guess it's probably moot, but scipy version is 1.4.1.
