### ISSUE TITLE
Model evaluation fails when using external embeddings

### ISSUE THREAD

**Issue by thllwg** [mozilla/TTS#497]
I'm currently trying to train a network with the current dev branch, using LibriTTS 360+100 with external embeddings. Training fails at the end of the first epoch, when the evaluation is conducted. 
   ```
--> TRAIN PERFORMACE -- EPOCH TIME: 1426.36 sec -- GLOBAL_STEP: 1855
     | > avg_decoder_loss: 1.14756
     | > avg_postnet_loss: 1.27054
     | > avg_stopnet_loss: 0.30356
     | > avg_decoder_coarse_loss: 1.10275
     | > avg_decoder_ddc_loss: 0.00487
     | > avg_ga_loss: 0.04375
     | > avg_loss: 3.56949
     | > avg_align_error: 0.93601
     | > avg_loader_time: 0.00657
     | > avg_step_time: 0.76924

 > EVALUATION

 ! Run is removed from /home/dobby/models/multi/LibriTTS/libritts_360_100-gst-ddc-bn-embeddings-August-14-2020_06+31AM-8b4eb25
Traceback (most recent call last):
  File "mozilla_voice_tts/bin/train_tts.py", line 714, in <module>
    main(args)
  File "mozilla_voice_tts/bin/train_tts.py", line 627, in main
    eval_avg_loss_dict = evaluate(model, criterion, ap, global_step, epoch)
  File "/home/dobby/thllwgTTS_try/thllwgtts/lib/python3.6/site-packages/torch-1.6.0-py3.6-linux-x86_64.egg/torch/autograd/grad_mode.py", line 15, in decorate_context
    return func(*args, **kwargs)
  File "mozilla_voice_tts/bin/train_tts.py", line 342, in evaluate
    text_input, text_lengths, mel_input, speaker_ids=speaker_ids, speaker_embeddings=speaker_embeddings)
  File "/home/dobby/thllwgTTS_try/thllwgtts/lib/python3.6/site-packages/torch-1.6.0-py3.6-linux-x86_64.egg/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/dobby/thllwgTTS_try/TTS/mozilla_voice_tts/tts/models/tacotron2.py", line 112, in forward
    speaker_embeddings = torch.unsqueeze(speaker_embeddings, 1)
TypeError: unsqueeze(): argument 'input' (position 1) must be Tensor, not NoneType
```
The reason is that the `speaker_mapping` passed to `evaluate` in `train_tts.py`.

**Comment by erogol** [comment]
interesting actually we run a sample training in tests, but it passes the testing.
