### ISSUE TITLE
RuntimeError: CUDA out of memory. Tried to allocate 2.00 MiB (GPU 0; 10.76 GiB total capacity; 9.59 GiB already allocated; 4.25 MiB free; 9.78 GiB reserved in total by PyTorch)

### ISSUE THREAD

**Issue by andrenatal** [mozilla/TTS#502]
I keep getting this error when training on different servers using a custom dataset. I got it when using: 

- `distributed_tts.py` on 4,3 and 2 RTX 2080TI 
- `train_tts.py` on 1 RTX 2080TI 
- `distributed_tts.py` on 1 GTX 1070
- `train_tts.py` on 1 GTX 1070

I managed to train in a different server on 1 GTX 1080 until completion.

Below is the stack. When I'm using `distributed_tts.py`, I get the error but the script does not exit and the other process remain running on the GPUs:

```

+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.64.00    Driver Version: 440.64.00    CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce RTX 208...  On   | 00000000:19:00.0 Off |                  N/A |
| 28%   27C    P8    22W / 250W |     12MiB / 11019MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce RTX 208...  On   | 00000000:1A:00.0 Off |                  N/A |
| 58%   88C    P2    71W / 250W |  10915MiB / 11019MiB |    100%      Default |
+-------------------------------+----------------------+----------------------+
|   2  GeForce RTX 208...  On   | 00000000:67:00.0 Off |                  N/A |
| 52%   84C    P2   102W / 250W |  10991MiB / 11019MiB |    100%      Default |
+-------------------------------+----------------------+----------------------+
|   3  GeForce RTX 208...  On   | 00000000:68:00.0 Off |                  N/A |
| 31%   47C    P8    25W / 250W |     12MiB / 11018MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    1     27800      C   python3                                    10903MiB |
|    2     27801      C   python3                                    10979MiB |
+-----------------------------------------------------------------------------+
```

```


 > TRAINING (2020-08-19 05:42:26)
/media/disk2/engines/TTS/tts_venv/lib/python3.6/site-packages/torch-1.6.0-py3.6-linux-x86_64.egg/torch/distributed/di
stributed_c10d.py:125: UserWarning: torch.distributed.reduce_op is deprecated, please use torch.distributed.ReduceOp
instead
  warnings.warn("torch.distributed.reduce_op is deprecated, please use "

   --> STEP: 10/13 -- GLOBAL_STEP: 25
     | > decoder_loss: 11.49612  (11.66776)
     | > postnet_loss: 12.56934  (12.94062)
     | > stopnet_loss: 0.68627  (0.70399)
     | > decoder_coarse_loss: 11.49253  (11.67952)
     | > decoder_ddc_loss: 0.00083  (0.00142)
     | > ga_loss: 0.02466  (0.04069)
     | > loss: 35.61561  (36.34546)
     | > align_error: 0.99221  (0.98766)
     | > avg_spec_length: 856.9
     | > avg_text_length: 127.1
     | > step_time: 2.0197
     | > loader_time: 0.02
     | > current_lr: 0.0001
Traceback (most recent call last):
  File "/media/disk2/engines/TTS/mozilla_voice_tts/bin/train_tts.py", line 714, in <module>
    main(args)
  File "/media/disk2/engines/TTS/mozilla_voice_tts/bin/train_tts.py", line 626, in main
    global_step, epoch, amp, speaker_mapping)
  File "/media/disk2/engines/TTS/mozilla_voice_tts/bin/train_tts.py", line 171, in train
    text_input, text_lengths, mel_input, mel_lengths, speaker_ids=speaker_ids, speaker_embeddings=speaker_embeddings)
  File "/media/disk2/engines/TTS/tts_venv/lib/python3.6/site-packages/torch-1.6.0-py3.6-linux-x86_64.egg/torch/nn/mod
ules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/media/disk2/engines/TTS/mozilla_voice_tts/tts/models/tacotron2.py", line 136, in forward
    decoder_outputs_backward, alignments_backward = self._coarse_decoder_pass(mel_specs, encoder_outputs, alignments,
 input_mask)
  File "/media/disk2/engines/TTS/mozilla_voice_tts/tts/models/tacotron_abstract.py", line 156, in _coarse_decoder_pas
s
  File "/media/disk2/engines/TTS/tts_venv/lib/python3.6/site-packages/torch-1.6.0-py3.6-linux-x86_64.egg/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/media/disk2/engines/TTS/mozilla_voice_tts/tts/layers/tacotron2.py", line 326, in forward
    decoder_output, attention_weights, stop_token = self.decode(memory)
  File "/media/disk2/engines/TTS/mozilla_voice_tts/tts/layers/tacotron2.py", line 282, in decode
    decoder_rnn_input, (self.decoder_hidden, self.decoder_cell))
  File "/media/disk2/engines/TTS/tts_venv/lib/python3.6/site-packages/torch-1.6.0-py3.6-linux-x86_64.egg/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/media/disk2/engines/TTS/tts_venv/lib/python3.6/site-packages/torch-1.6.0-py3.6-linux-x86_64.egg/torch/nn/modules/rnn.py", line 969, in forward
    self.bias_ih, self.bias_hh,
RuntimeError: CUDA out of memory. Tried to allocate 2.00 MiB (GPU 3; 10.76 GiB total capacity; 9.57 GiB already allocated; 2.94 MiB free; 9.77 GiB reserved in total by PyTorch)
 ! Run is kept in /media/disk2/corpora/perola/outputs_treino/perola-August-19-2020_05+40AM-3424181
Traceback (most recent call last):
  File "/media/disk2/engines/TTS/mozilla_voice_tts/bin/train_tts.py", line 714, in <module>
    main(args)
  File "/media/disk2/engines/TTS/mozilla_voice_tts/bin/train_tts.py", line 626, in main
    global_step, epoch, amp, speaker_mapping)
  File "/media/disk2/engines/TTS/mozilla_voice_tts/bin/train_tts.py", line 171, in train
    text_input, text_lengths, mel_input, mel_lengths, speaker_ids=speaker_ids, speaker_embeddings=speaker_embeddings)
  File "/media/disk2/engines/TTS/tts_venv/lib/python3.6/site-packages/torch-1.6.0-py3.6-linux-x86_64.egg/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/media/disk2/engines/TTS/mozilla_voice_tts/tts/models/tacotron2.py", line 136, in forward
    decoder_outputs_backward, alignments_backward = self._coarse_decoder_pass(mel_specs, encoder_outputs, alignments, input_mask)
  File "/media/disk2/engines/TTS/mozilla_voice_tts/tts/models/tacotron_abstract.py", line 156, in _coarse_decoder_pass
    encoder_outputs.detach(), mel_specs, input_mask)
  File "/media/disk2/engines/TTS/tts_venv/lib/python3.6/site-packages/torch-1.6.0-py3.6-linux-x86_64.egg/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/media/disk2/engines/TTS/mozilla_voice_tts/tts/layers/tacotron2.py", line 326, in forward
    decoder_output, attention_weights, stop_token = self.decode(memory)
  File "/media/disk2/engines/TTS/mozilla_voice_tts/tts/layers/tacotron2.py", line 293, in decode
    stop_token = self.stopnet(stopnet_input.detach())
  File "/media/disk2/engines/TTS/tts_venv/lib/python3.6/site-packages/torch-1.6.0-py3.6-linux-x86_64.egg/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/media/disk2/engines/TTS/tts_venv/lib/python3.6/site-packages/torch-1.6.0-py3.6-linux-x86_64.egg/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/media/disk2/engines/TTS/tts_venv/lib/python3.6/site-packages/torch-1.6.0-py3.6-linux-x86_64.egg/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/media/disk2/engines/TTS/tts_venv/lib/python3.6/site-packages/torch-1.6.0-py3.6-linux-x86_64.egg/torch/nn/modules/dropout.py", line 58, in forward
    return F.dropout(input, self.p, self.training, self.inplace)
  File "/media/disk2/engines/TTS/tts_venv/lib/python3.6/site-packages/torch-1.6.0-py3.6-linux-x86_64.egg/torch/nn/functional.py", line 973, in dropout
    else _VF.dropout(input, p, training))
RuntimeError: CUDA out of memory. Tried to allocate 2.00 MiB (GPU 0; 10.76 GiB total capacity; 9.68 GiB already allocated; 4.25 MiB free; 9.77 GiB reserved in total by PyTorch)
```

**Comment by erogol** [comment]
did you successfully train this model with the same dataset before?

**Comment by andrenatal** [comment]
Yes, as I said, in a third server in a single gpu (gtx 1080), but that was
few weeks ago before rebasing.

**Comment by erogol** [comment]
so is there any difference except the rebase?

**Comment by andrenatal** [comment]
No, even the config file is the same.

**Comment by andrenatal** [comment]
The working commit was from Aug 3rd.

**Comment by erogol** [comment]
Try a smaller batch size. Easy solution.

**Comment by andrenatal** [comment]
I tried, many times. I get it even with a batch of 4.

**Comment by george-roussos** [comment]
Maybe the longest spectrogram doesn't fit. Sometimes it happens to me. 🙂

**Comment by andrenatal** [comment]
I thought this @george-roussos too, but I managed to train with this dataset before :(

**Comment by andrenatal** [comment]
That was exactly the problem. I have some files with more than 15s of duration, and those doesn't fit on `RTX 2080TI` neither `GTX 1070`, but it does on `GTX 1080`,  where I managed to train initially.
