### ISSUE TITLE
Encountering ' RuntimeError: 'lengths' argument should be a 1D CPU int64 tensor, but got 1D cuda:0 Long tensor' when trying to run 'train_tts.py'

### ISSUE THREAD

**Issue by khalilRhouma** [mozilla/TTS#567]
I have recently discovered your TTS repo. When I started a run with 'train_tts.py' using LJSpeech to explore your work I encounter this error:
`2020-11-11 15:37:37.753288: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory
2020-11-11 15:37:37.753334: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
 > Using CUDA:  True
 > Number of GPUs:  1
fatal: not a git repository (or any of the parent directories): .git
 > Git Hash: 0000000
 > Experiment folder: output/ljspeech-ddc-November-11-2020_03+37PM-0000000
fatal: not a git repository (or any of the parent directories): .git
 > Setting up Audio Processor...
 | > sample_rate:22050
 | > num_mels:80
 | > min_level_db:-100
 | > frame_shift_ms:None
 | > frame_length_ms:None
 | > ref_level_db:20
 | > fft_size:1024
 | > power:1.5
 | > preemphasis:0.0
 | > griffin_lim_iters:60
 | > signal_norm:True
 | > symmetric_norm:True
 | > mel_fmin:50.0
 | > mel_fmax:7600.0
 | > spec_gain:1.0
 | > stft_pad_mode:reflect
 | > max_norm:4.0
 | > clip_norm:True
 | > do_trim_silence:True
 | > trim_db:60
 | > do_sound_norm:False
 | > stats_path:LJSpeech-1.1/scale_stats.npy
 | > hop_length:256
 | > win_length:1024
 | > Found 12000 files in /home/khalil/Mozilla_TTS/LJSpeech-1.1
 > Using model: Tacotron2

 > Model has 47914548 parameters

 > EPOCH: 0/1000

 > Number of output frames: 7

 > DataLoader initialization
 | > Use phonemes: True
   | > phoneme language: en-us
 | > Number of instances : 12000
 | > Max length sequence: 187
 | > Min length sequence: 5
 | > Avg length sequence: 98.45766666666667
 | > Num. instances discarded by max-min (max=153, min=6) seq limits: 438
 | > Batch group size: 256.

 > TRAINING (2020-11-11 15:37:43) 
 ! Run is removed from output/ljspeech-ddc-November-11-2020_03+37PM-0000000
Traceback (most recent call last):
  File "TTS/TTS/bin/train_tts.py", line 715, in <module>
    main(args)
  File "TTS/TTS/bin/train_tts.py", line 627, in main
    global_step, epoch, amp, speaker_mapping)
  File "TTS/TTS/bin/train_tts.py", line 163, in train
    text_input, text_lengths, mel_input, mel_lengths, speaker_ids=speaker_ids, speaker_embeddings=speaker_embeddings)
  File "/home/khalil/anaconda3/envs/mozilla_tts/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/khalil/anaconda3/envs/mozilla_tts/lib/python3.7/site-packages/TTS-0.0.5+79ce06c-py3.7-linux-x86_64.egg/TTS/tts/models/tacotron2.py", line 102, in forward
    encoder_outputs = self.encoder(embedded_inputs, text_lengths)
  File "/home/khalil/anaconda3/envs/mozilla_tts/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/khalil/anaconda3/envs/mozilla_tts/lib/python3.7/site-packages/TTS-0.0.5+79ce06c-py3.7-linux-x86_64.egg/TTS/tts/layers/tacotron2.py", line 106, in forward
    batch_first=True)
  File "/home/khalil/anaconda3/envs/mozilla_tts/lib/python3.7/site-packages/torch/nn/utils/rnn.py", line 244, in pack_padded_sequence
    _VF._pack_padded_sequence(input, lengths, batch_first)
RuntimeError: 'lengths' argument should be a 1D CPU int64 tensor, but got 1D cuda:0 Long tensor`

**Cloned the TTS repo with**: `git clone https://github.com/mozilla/TTS`
**Pytorch version:** 1.7.0

PS: I have created an environment and Installed all  packages requirements

**Comment by khalilRhouma** [comment]
I think the issue is related to PyTorch version (pytorch 1.7.0) because I found the same [issue](https://github.com/pytorch/pytorch/issues/43227) in Pytorch GitHub issues and [this is the fix for it](https://github.com/joeynmt/joeynmt/pull/119/commits/ef1b0f081fedfcf83ce39cd2f27dcc33d3cbb2d1)
