### ISSUE TITLE
librosa.util.exceptions.ParameterError: Audio buffer is not finite everywhere

### ISSUE THREAD

**Issue by tsungruihon** [mozilla/TTS#568]
When i tried to train `multiband-melgan`, this error happened. May someone could give me a hint ? Thanks.

```
   --> TRAIN PERFORMACE -- EPOCH TIME: 18.99 sec -- GLOBAL_STEP: 188
     | > avg_G_stft_loss_mg: 4.12732
     | > avg_G_stft_loss_sc: 17.31412
     | > avg_G_subband_stft_loss_mg: 3.80862
     | > avg_G_subband_stft_loss_sc: 16.00352
     | > avg_G_loss: 20.62680
     | > avg_G_gen_loss: 20.62680
     | > avg_G_adv_loss: 0.00000
     | > avg_loader_time: 6.44516
     | > avg_step_time: 0.20042

 > EVALUATION

 ! Run is removed from /home/jovyan/data2/data/peter/TTS_test_3/TTS/TTS/vocoder/pwgan_output/multiband-melgan-November-12-2020_12+15PM-540d811
Traceback (most recent call last):
  File "bin/train_vocoder.py", line 650, in <module>
    main(args)
  File "bin/train_vocoder.py", line 556, in main
    global_step, epoch)
  File "/home/jovyan/data1/peter/anaconda3/envs/tts/lib/python3.6/site-packages/torch/autograd/grad_mode.py", line 49, in decorate_no_grad
    return func(*args, **kwargs)
  File "bin/train_vocoder.py", line 426, in evaluate
    figures = plot_results(y_hat, y_G, ap, global_step, 'eval')
  File "/home/jovyan/data2/data/peter/TTS_test_3/TTS/TTS/vocoder/utils/generic_utils.py", line 18, in plot_results
    spec_fake = ap.melspectrogram(y_hat).T
  File "/home/jovyan/data2/data/peter/TTS_test_3/TTS/TTS/utils/audio.py", line 227, in melspectrogram
    D = self._stft(y)
  File "/home/jovyan/data2/data/peter/TTS_test_3/TTS/TTS/utils/audio.py", line 264, in _stft
    pad_mode=self.stft_pad_mode,
  File "/home/jovyan/data1/peter/anaconda3/envs/tts/lib/python3.6/site-packages/librosa/core/spectrum.py", line 215, in stft
    util.valid_audio(y)
  File "/home/jovyan/data1/peter/anaconda3/envs/tts/lib/python3.6/site-packages/librosa/util/utils.py", line 275, in valid_audio
    raise ParameterError('Audio buffer is not finite everywhere')
librosa.util.exceptions.ParameterError: Audio buffer is not finite everywhere
```

**Comment by mdrame20** [comment]
HI @tsungruihon were you able to fix this? I'm having the same issue

**Comment by OswaldoBornemann** [comment]
@mdrame20 still face the problem

**Comment by Aymen08** [comment]
Hi @tsungruihon ,
Your error appears after how many epochs ?

**Comment by OswaldoBornemann** [comment]
@Aymen08 It happened after one epoch. But when i i change to another gpu server, the error disappeared. Weird.

**Comment by Aymen08** [comment]
@tsungruihon  nice, and the other gpu is in the same machine ?

**Comment by zubairahmed-ai** [comment]
@tsungruihon @Aymen08 Did you guys manage to fix this? I am using [CheckSpectogram notebook](https://github.com/coqui-ai/TTS/blob/main/notebooks/dataset_analysis/CheckSpectrograms.ipynb) for training AlignTTS model and get this error on the 96th/100 files in my dataset and I have no clue why when all other files before this are identical, I have triple-checked it in Audacity and even trimmed some silence out of it in the beginning of the clip but no joy

![image](https://user-images.githubusercontent.com/1317442/121860691-8a665600-cd12-11eb-8f33-4de3adefa3de.png)

**Comment by tiomaldy** [comment]
Someone solve this ?

**Comment by zubairahmed-ai** [comment]
> Someone solve this ?

@tiomaldy I commented that line in the code that checks and ran my training, so far no issue I suggest you do the same

**Comment by tiomaldy** [comment]
I can t understando you.
