### ISSUE TITLE
RuntimeError: Error opening 'LJSpeech-1.1/wavs/\ufeffH_2.wav': System error.

### ISSUE THREAD

**Issue by xoxoxo13102020** [mozilla/TTS#584]
I got this error when I tried to run compute_statistics.py

 ```
45%|█████████████████████████████▎                                   | 9028/20032 [04:05<04:59, 36.70it/s]
Traceback (most recent call last):
  File "TTS/compute_statistics.py", line 85, in <module>
    main()
  File "TTS/compute_statistics.py", line 43, in main
    wav = ap.load_wav(item[1])
  File "/usr/local/lib/python3.6/dist-packages/TTS-0.0.3+b1935c9-py3.6.egg/TTS/utils/audio.py", line 311, in load_wav
    x, sr = sf.read(filename)
  File "/usr/local/lib/python3.6/dist-packages/soundfile.py", line 257, in read
    subtype, endian, format, closefd) as f:
  File "/usr/local/lib/python3.6/dist-packages/soundfile.py", line 629, in __init__
    self._file = self._open(file, mode_int, closefd)
  File "/usr/local/lib/python3.6/dist-packages/soundfile.py", line 1184, in _open
    "Error opening {0!r}: ".format(self.name))
  File "/usr/local/lib/python3.6/dist-packages/soundfile.py", line 1357, in _error_check
    raise RuntimeError(prefix + _ffi.string(err_str).decode('utf-8-sig', 'replace'))
RuntimeError: Error opening 'LJSpeech-1.1/wavs/\ufeffH_2.wav': System error.
```

how to fix this?

**Comment by erogol** [comment]
almost all issues you create, here is the error and "how to fix it?" 

It is not a customer support center. You need to provide replicable errors, your platform details, what you have tried so far etc. 

Don't expect people to help you every time you put something out there. Our time is as valuable as yours.
