### ISSUE TITLE
Melgan training with use_cache: true and num_loader_workers > 0 errors on Windows

### ISSUE THREAD

**Issue by lasa01** [mozilla/TTS#611]
Trying to train melgan on Windows with `"use_cache": true` in config results in the following error:
```
> Using CUDA:  True
 > Number of GPUs:  1
 > Git Hash: 7cf2052
 > Experiment folder: ...
 > Loading wavs from: ...
 > Setting up Audio Processor...
 | > sample_rate:22050
 | > num_mels:80
 | > min_level_db:-100
 | > frame_shift_ms:None
 | > frame_length_ms:None
 | > ref_level_db:0
 | > fft_size:1024
 | > power:None
 | > preemphasis:0.0
 | > griffin_lim_iters:None
 | > signal_norm:True
 | > symmetric_norm:True
 | > mel_fmin:50.0
 | > mel_fmax:7600.0
 | > spec_gain:1.0
 | > stft_pad_mode:reflect
 | > max_norm:4.0
 | > clip_norm:True
 | > do_trim_silence:True
 | > trim_db:60
 | > do_sound_norm:False
 | > stats_path: ...
 | > hop_length:256
 | > win_length:1024
 > Generator Model: multiband_melgan_generator
 > Discriminator Model: melgan_multiscale_discriminator
 > Generator has 2539448 parameters
 > Discriminator has 4354998 parameters

 > EPOCH: 0/10000
 > Using CUDA:  True
 > Number of GPUs:  1

 > TRAINING (2020-12-29 21:26:49)
 > Using CUDA:  True
 > Number of GPUs:  1
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Program Files\Python36\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Program Files\Python36\lib\multiprocessing\spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input
 ! Run is removed from ...
Traceback (most recent call last):
  File "TTS\bin\train_vocoder_gan.py", line 654, in <module>
    main(args)
  File "TTS\bin\train_vocoder_gan.py", line 559, in main
    epoch)
  File "TTS\bin\train_vocoder_gan.py", line 100, in train
    for num_iter, data in enumerate(data_loader):
  File "d:\lasa\Code\tts_venv\lib\site-packages\torch\utils\data\dataloader.py", line 279, in __iter__
    return _MultiProcessingDataLoaderIter(self)
  File "d:\lasa\Code\tts_venv\lib\site-packages\torch\utils\data\dataloader.py", line 719, in __init__
    w.start()
  File "C:\Program Files\Python36\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "C:\Program Files\Python36\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Program Files\Python36\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Program Files\Python36\lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Program Files\Python36\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: can't pickle weakref objects
```

The problem can be worked around by either setting `num_loader_workers` and `num_val_loader_workers` to 0, or by disabling `use_cache`.

The error seems to be related to pickling `self.manager` defined in `TTS\vocoder\datasets\gan_dataset.py` line 54.
Looks like the manager is not picklable.

Looks like the manager is not used anywhere else other than the next line though, so this change:
```diff
diff --git a/TTS/vocoder/datasets/gan_dataset.py b/TTS/vocoder/datasets/gan_dataset.py
index af23fbf..3cc0183 100644
--- a/TTS/vocoder/datasets/gan_dataset.py
+++ b/TTS/vocoder/datasets/gan_dataset.py
@@ -51,8 +51,7 @@ class GANDataset(Dataset):
             self.create_feature_cache()

     def create_feature_cache(self):
-        self.manager = Manager()
-        self.cache = self.manager.list()
+        self.cache = Manager().list()
         self.cache += [None for _ in range(len(self.item_list))]

     @staticmethod
```
fixes the issue.

**Comment by erogol** [comment]
it doesn't make sense to me but it is windows so I don't expect it to :)
