### ISSUE TITLE
problem with the installation on python 3.8 and 3.6

### ISSUE THREAD

**Issue by pathnirvana** [mozilla/TTS#627]
```
git clone https://github.com/mozilla/TTS
pip install -e .
tts --list
```

gives the following error

``` 
tts --list
Traceback (most recent call last):
  File "/home/janaka/mozilla/lib/python3.8/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/home/janaka/mozilla/lib/python3.8/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/janaka/mozilla/lib/python3.8/site-packages/pkg_resources/__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (numba 0.48.0 (/home/janaka/mozilla/lib/python3.8/site-packages), Requirement.parse('numba>=0.49'), {'umap-learn'})

During handling of the above exception, another exception occurred:
```

**Comment by pathnirvana** [comment]
on python 3.6 fails with the following error
```
ERROR: tensorflow 2.3.1 has requirement numpy<1.19.0,>=1.16.0, but you'll have numpy 1.19.5 which is incompatible.
ERROR: panel 0.9.7 has requirement bokeh>=2.1, but you'll have bokeh 1.4.0 which is incompatible.
```

**Comment by pathnirvana** [comment]
worked on python 3.7 - closing
