### ISSUE TITLE
Loading JSON tts config broken

### ISSUE THREAD

**Issue by mweinelt** [mozilla/TTS#631]
I downloaded the Tacotron DCA model (https://github.com/mozilla/TTS/releases/download/v0.0.9/tts_models--en--ljspeech--tacotron2-DCA.rar) for 0.0.9 and unpacked it and modified the stats_path, which was hardcoded to your homedir.

Passing the config to tts-server it fails to decode the JSON:

```pytb
Traceback (most recent call last):
  File "/nix/store/dadsa5nz9j79hwlnp4090ggdl55jgs8g-tts-0.0.9/bin/.tts-server-wrapped", line 6, in <module>
    from TTS.server.server import main
  File "/nix/store/dadsa5nz9j79hwlnp4090ggdl55jgs8g-tts-0.0.9/lib/python3.8/site-packages/TTS/server/server.py", line 77, in <module>
    synthesizer = Synthesizer(args.tts_checkpoint, args.tts_config, args.vocoder_checkpoint, args.vocoder_config, args.use_cuda)
  File "/nix/store/dadsa5nz9j79hwlnp4090ggdl55jgs8g-tts-0.0.9/lib/python3.8/site-packages/TTS/utils/synthesizer.py", line 46, in __init__
    self.load_tts(tts_checkpoint, tts_config,
  File "/nix/store/dadsa5nz9j79hwlnp4090ggdl55jgs8g-tts-0.0.9/lib/python3.8/site-packages/TTS/utils/synthesizer.py", line 80, in load_tts
    self.tts_config = load_config(tts_config)
  File "/nix/store/dadsa5nz9j79hwlnp4090ggdl55jgs8g-tts-0.0.9/lib/python3.8/site-packages/TTS/utils/io.py", line 46, in load_config
    data = read_json_with_comments(config_path)
  File "/nix/store/dadsa5nz9j79hwlnp4090ggdl55jgs8g-tts-0.0.9/lib/python3.8/site-packages/TTS/utils/io.py", line 30, in read_json_with_comments
    data = json.loads(input_str)
  File "/nix/store/2wwb85hrvvfzkhrlwcj3pqi60nlbi9cq-python3-3.8.7/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/nix/store/2wwb85hrvvfzkhrlwcj3pqi60nlbi9cq-python3-3.8.7/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/nix/store/2wwb85hrvvfzkhrlwcj3pqi60nlbi9cq-python3-3.8.7/lib/python3.8/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Invalid control character at: line 32 column 17 (char 788)
```

I piped the config through jq to pretty print it and make sure it is in fact valid JSON.

```json
{
  "github_branch": "* dynamic_conv_attention",
  "model": "Tacotron2",
  "run_name": "ljspeech-dcattn",
  "run_description": "tacotron2 with dynamic convolution attention.",
  "audio": {
    "fft_size": 1024,
    "win_length": 1024,
    "hop_length": 256,
    "frame_length_ms": null,
    "frame_shift_ms": null,
    "sample_rate": 22050,
    "preemphasis": 0,
    "ref_level_db": 20,
    "do_trim_silence": true,
    "trim_db": 60,
    "power": 1.5,
    "griffin_lim_iters": 60,
    "num_mels": 80,
    "mel_fmin": 50,
    "mel_fmax": 7600,
    "spec_gain": 1,
    "signal_norm": true,
    "min_level_db": -100,
    "symmetric_norm": true,
    "max_norm": 4,
    "clip_norm": true,
    "stats_path": "tts/scale_stats.npy"
  },
  "distributed": {
    "backend": "nccl",
    "url": "tcp://localhost:54321"
  },
  "reinit_layers": [],
  "batch_size": 64,
  "eval_batch_size": 16,
  "r": 2,
  "gradual_training": null,
  "mixed_precision": true,
  "loss_masking": true,
  "decoder_loss_alpha": 0.25,
  "postnet_loss_alpha": 0.25,
  "postnet_diff_spec_alpha": 0,
  "decoder_diff_spec_alpha": 0,
  "decoder_ssim_alpha": 0.25,
  "postnet_ssim_alpha": 0.25,
  "ga_alpha": 0,
  "stopnet_pos_weight": 15,
  "run_eval": true,
  "test_delay_epochs": 10,
  "test_sentences_file": null,
  "noam_schedule": true,
  "grad_clip": 0.05,
  "epochs": 1000,
  "lr": 0.001,
  "wd": 1e-06,
  "warmup_steps": 4000,
  "seq_len_norm": false,
  "memory_size": -1,
  "prenet_type": "original",
  "prenet_dropout": true,
  "attention_type": "dynamic_convolution",
  "attention_heads": 4,
  "attention_norm": "softmax",
  "windowing": false,
  "use_forward_attn": false,
  "forward_attn_mask": false,
  "transition_agent": false,
  "location_attn": false,
  "bidirectional_decoder": false,
  "double_decoder_consistency": false,
  "ddc_r": 7,
  "stopnet": true,
  "separate_stopnet": true,
  "print_step": 25,
  "tb_plot_step": 100,
  "print_eval": false,
  "save_step": 10000,
  "checkpoint": true,
  "tb_model_param_stats": false,
  "text_cleaner": "phoneme_cleaners",
  "enable_eos_bos_chars": false,
  "num_loader_workers": 4,
  "num_val_loader_workers": 4,
  "batch_group_size": 4,
  "min_seq_len": 6,
  "max_seq_len": 180,
  "compute_input_seq_cache": true,
  "output_path": "/data/rw/home/Trainings/LJSpeech/",
  "phoneme_cache_path": "~/phoneme_cache/",
  "use_phonemes": true,
  "phoneme_language": "en-us",
  "use_speaker_embedding": false,
  "use_gst": false,
  "use_external_speaker_embedding_file": false,
  "external_speaker_embedding_file": "../../speakers-vctk-en.json",
  "gst": {
    "gst_style_input": null,
    "gst_embedding_dim": 512,
    "gst_num_heads": 4,
    "gst_style_tokens": 10,
    "gst_use_speaker_embedding": false
  },
  "datasets": [
    {
      "name": "ljspeech",
      "path": "/root/LJSpeech-1.1/",
      "meta_file_train": "metadata.csv",
      "meta_file_val": null
    }
  ]
}
```

I then noticed the alternate code path to interpret it as YAML, which just worked.

Something is clearly off with the code path beginning with `read_json_with_comments`.

**Comment by mweinelt** [comment]
This happens because the second substitution

https://github.com/mozilla/TTS/blob/54139f6333194330b1efbda9c6c78f82e14a0d60/TTS/utils/io.py#L29

transforms this

```json
  "distributed": {
    "backend": "nccl",
    "url": "tcp://localhost:54321"
  },
```

into this

```json
  "distributed": {
    "backend": "nccl",
    "url": "tcp:
  },
```

**Comment by mweinelt** [comment]
Did you close this by accident? Because the problem still exists on `dev`.

**Comment by atherfawaz** [comment]
Similar issue on my end.  Was trying to run ExtractTTSSpectrogram.ipynb but the hardcoded `config.json` file could not be found. Not sure where to look for it either.

`CONFIG_PATH = "/home/erogol/Models/LJSpeech/ljspeech-March-17-2020_01+16AM-871588c/config.json"`
