### ISSUE TITLE
CUDA error: CUBLAS_STATUS_EXECUTION_FAILED when calling `cublasGemmEx` on GeForce GTX 1650 under WSL2

### ISSUE THREAD

**Issue by GuyPaddock** [mozilla/TTS#666]
Something causes TTS to fail to train on GeForce GTX 1650 cards under WSL2. Training works under CPU-based training fine, but it doesn't work using CUDA in WSL2.

The system in question is running the latest Windows 10 Dev insider build. It has been configured following all the steps under https://docs.nvidia.com/cuda/wsl-user-guide/index.html. It also has the specific version of CUDA libraries that TensorFlow demanded:

```
apt-get install cuda-cudart-10-1
apt-get install cuda-cusparse-10-0
apt-get install cuda-cudart-10-1
apt-get install -y cuda-toolkit-10-1
apt-get install libcublas10=10.2.1.243-1 libcublas-dev=10.2.1.243-1 cuda-libraries-10-1 cuda-libraries-dev-10-1
```

Output from the following script:
```python
import tensorflow as tf

tf.config.list_physical_devices('GPU')
```

Results in this output:
```
2021-02-21 21:29:20.944075: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
2021-02-21 21:29:21.764417: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcuda.so.1
2021-02-21 21:29:22.116036: E tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:968] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2021-02-21 21:29:22.116429: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1716] Found device 0 with properties:
pciBusID: 0000:01:00.0 name: GeForce GTX 1650 computeCapability: 7.5
coreClock: 1.56GHz coreCount: 16 deviceMemorySize: 4.00GiB deviceMemoryBandwidth: 119.24GiB/s
2021-02-21 21:29:22.116492: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
2021-02-21 21:29:22.120803: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcublas.so.10
2021-02-21 21:29:22.126134: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcufft.so.10
2021-02-21 21:29:22.127236: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcurand.so.10
2021-02-21 21:29:22.134919: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusolver.so.10
2021-02-21 21:29:22.137583: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusparse.so.10
2021-02-21 21:29:22.146202: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudnn.so.7
2021-02-21 21:29:22.147391: E tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:968] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2021-02-21 21:29:22.148957: E tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:968] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2021-02-21 21:29:22.149538: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1858] Adding visible gpu devices: 0
```

But training of the model results in:
```
2021-02-21 21:34:07.978266: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
 > Using CUDA:  True
 > Number of GPUs:  1
   >  Mixed precision mode is ON
 > Git Hash: e9e0784
 > Experiment folder: /path/to/my/project
 > Setting up Audio Processor...
 | > sample_rate:22050
 | > resample:False
 | > num_mels:80
 | > min_level_db:-100
 | > frame_shift_ms:None
 | > frame_length_ms:None
 | > ref_level_db:20
 | > fft_size:1024
 | > power:1.5
 | > preemphasis:0.0
 | > griffin_lim_iters:60
 | > signal_norm:True
 | > symmetric_norm:True
 | > mel_fmin:50.0
 | > mel_fmax:7600.0
 | > spec_gain:1.0
 | > stft_pad_mode:reflect
 | > max_norm:4.0
 | > clip_norm:True
 | > do_trim_silence:True
 | > trim_db:60
 | > do_sound_norm:False
 | > stats_path:/path/to/my/project/scale_stats.npy
 | > hop_length:256
 | > win_length:1024
 | > Found 101 files in /path/to/my/project
 > Using model: Tacotron2

 > Model has 47914548 parameters

 > DataLoader initialization
 | > Use phonemes: True
   | > phoneme language: en-us
 | > Number of instances : 100
 | > Max length sequence: 150
 | > Min length sequence: 3
 | > Avg length sequence: 39.07
 | > Num. instances discarded by max-min (max=153, min=6) seq limits: 3
 | > Batch group size: 128.

 > EPOCH: 0/1000

 > Number of output frames: 7

 > TRAINING (2021-02-21 21:34:13)
 ! Run is removed from /path/to/my/project
Traceback (most recent call last):
  File "./TTS/bin/train_tacotron.py", line 721, in <module>
    main(args)
  File "./TTS/bin/train_tacotron.py", line 619, in main
    train_avg_loss_dict, global_step = train(train_loader, model,
  File "./TTS/bin/train_tacotron.py", line 193, in train
    scaler.scale(loss_dict['loss']).backward()
  File "/path/to/moz-tts/mozilla-tts/lib/python3.8/site-packages/torch/tensor.py", line 221, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/path/to/moz-tts/mozilla-tts/lib/python3.8/site-packages/torch/autograd/__init__.py", line 130, in backward
    Variable._execution_engine.run_backward(
RuntimeError: CUDA error: CUBLAS_STATUS_EXECUTION_FAILED when calling `cublasGemmEx( handle, opa, opb, m, n, k, &falpha, a, CUDA_R_16F, lda, b, CUDA_R_16F, ldb, &fbeta, c, CUDA_R_16F, ldc, CUDA_R_32F, CUBLAS_GEMM_DFALT_TENSOR_OP)`
```

**Comment by GuyPaddock** [comment]
Looks like this may be related to GPU memory :/ The 1650 only has 4 GB of RAM.

I was using the default `config.json`. If I change this section:
```
    "batch_size": 32,
    "eval_batch_size":16,
    "r": 7,
    "gradual_training": [[0, 7, 64], [1, 5, 64], [50000, 3, 32], [130000, 2, 32], [290000, 1, 32]],
    "mixed_precision": true,
```

So it reads:
```
    "batch_size": 12,
    "eval_batch_size":6,
    "r": 7,
    "gradual_training": null,
    "mixed_precision": false,
```

The error goes away. But, not sure whether the training will actually be useful.
