### ISSUE TITLE
Error during training: json.decoder.JSONDecodeError: Invalid \escape: line 3 column 78 (char 107)

### ISSUE THREAD

**Issue by luis-vera** [mozilla/TTS#671]
Hi

While I was training I got erro message about RunTimeError: **CUDA out of memory**. Tried to allocate 20.00 MiB (GPU 0; 11.00 GiB total capacity; 8.11 GiB already allocated; 7.74 MiB free; 8.30 GiB reserved in total by PyTorch)

I found this error is solved if I reduce batch size. Now I was using batch_size = 4 and eval_batch_size = 4. But when I reduced this value and I executed:

**python TTS/bin/train_tacotron.py --continue_path Models/LJSpeech/ljspeech-ddc-February-19-2021_11+37AM-e9e0784**

(README indicates I must type run directory)

The error was:

**2021-02-25 10:32:05.110659: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cudart64_101.dll
 > Using CUDA:  True
 > Number of GPUs:  1
 > Training continues for Models/LJSpeech/ljspeech-ddc-February-19-2021_11+37AM-e9e0784
Traceback (most recent call last):
  File "TTS/bin/train_tacotron.py", line 688, in <module>
    c = load_config(args.config_path)
  File "c:\users\voice-trainner\proyecto\tts\TTS\utils\io.py", line 46, in load_config
    data = read_json_with_comments(config_path)
  File "c:\users\voice-trainner\proyecto\tts\TTS\utils\io.py", line 30, in read_json_with_comments
    data = json.loads(input_str)
  File "C:\Users\Voice-trainner\anaconda3\envs\TF2\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Voice-trainner\anaconda3\envs\TF2\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Voice-trainner\anaconda3\envs\TF2\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Invalid \escape: line 3 column 78 (char 107)**

What it could have happened?
Thanks a lot for your help

**Comment by luis-vera** [comment]
The weird thing that is not a json file problem because I execute train_tacotron.py from zero again and the training stage started without problems. So maybe It's not a json problem.
