### ISSUE TITLE
OSError: sndfile library not found

### ISSUE THREAD

**Issue by GuyPaddock** [mozilla/TTS#683]
I've just spun up a new Tensorflow-optimized VM on GCP and am getting a new install of Mozilla TTS going inside. It looks like the `requirements.txt` might be missing `sndfile` as a dependency.

Here's what I ran prior to trying to start training:
```
git clone https://github.com/mozilla/TTS.git mozilla-tts-dev
virtualenv --python=python3 ./mozilla-tts-dev
cd mozilla-tts-dev
git checkout dev
./bin/pip install -e .
```

Then, when I ran `./bin/python3 ./TTS/bin/train_tacotron.py`, I got:
```
Traceback (most recent call last):
  File "./TTS/bin/train_tacotron.py", line 23, in <module>
    from TTS.tts.utils.visual import plot_alignment, plot_spectrogram
  File "/mnt/mozilla-tts-data/mozilla-tts-dev/TTS/tts/utils/visual.py", line 1, in <module>
    import librosa
  File "/mnt/mozilla-tts-data/mozilla-tts-dev/lib/python3.6/site-packages/librosa/__init__.py", line 12, in <module>
    from . import core
  File "/mnt/mozilla-tts-data/mozilla-tts-dev/lib/python3.6/site-packages/librosa/core/__init__.py", line 126, in <module>
    from .audio import *  # pylint: disable=wildcard-import
  File "/mnt/mozilla-tts-data/mozilla-tts-dev/lib/python3.6/site-packages/librosa/core/audio.py", line 10, in <module>
    import soundfile as sf
  File "/mnt/mozilla-tts-data/mozilla-tts-dev/lib/python3.6/site-packages/soundfile.py", line 142, in <module>
    raise OSError('sndfile library not found')
```

**Comment by lexkoro** [comment]
You are missing libsndfile1 on your system. 
Try `sudo apt-get install libsndfile1`

Also you might want to move over to https://github.com/coqui-ai/TTS as it is now the active repository regarding TTS (more info here https://discourse.mozilla.org/t/coqui-ai-is-here/77027)
