### ISSUE TITLE
`bidirectional_decoder` appears broken in dev

### ISSUE THREAD

**Issue by GuyPaddock** [mozilla/TTS#685]
With the latest dev (547bfc4ce99e7782f98d0403429d15ec23cdc91d), trying to use `bidirectional_decoder` yields the following error during training:
```
Traceback (most recent call last):
  File "./TTS/bin/train_tacotron.py", line 664, in <module>
    main(args)
  File "./TTS/bin/train_tacotron.py", line 634, in main
    scaler_st)
  File "./TTS/bin/train_tacotron.py", line 165, in train
    text_input, text_lengths, mel_input, mel_lengths, speaker_ids=speaker_ids, speaker_embeddings=speaker_embeddings)
  File "/mnt/mozilla-tts-data/mozilla-tts-dev/lib/python3.6/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/mnt/mozilla-tts-data/mozilla-tts-dev/TTS/tts/models/tacotron2.py", line 181, in forward
    decoder_outputs_backward, alignments_backward = self._backward_pass(mel_specs, encoder_outputs, input_mask)
  File "/mnt/mozilla-tts-data/mozilla-tts-dev/TTS/tts/models/tacotron_abstract.py", line 153, in _backward_pass
    self.speaker_embeddings_projected)
  File "/mnt/mozilla-tts-data/mozilla-tts-dev/lib/python3.6/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
TypeError: forward() takes 4 positional arguments but 5 were given
```

Are additional parameters required in the `config.json` file?

**Comment by GuyPaddock** [comment]
Looks like my issue is a dupe of https://github.com/mozilla/TTS/issues/618
