### ISSUE TITLE
AssertionError while converting Tacotron2 Pytorch model to TF

### ISSUE THREAD

**Issue by khalilRhouma** [mozilla/TTS#686]
I am trying to improve inference response time, I read from your comments that converting Pytorch model to TF will improve TTS inference, so when I tried to run  `convert_tacotron2_torch_to_tf.py` on Tacotron2 checkpoint I got this AssertionError  and I didn't get it where is the problem exactly.  This is the log below :
```
  2021-03-16 16:29:00.636264: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1Traceback (most recent call last):
  File "/home/khalil/anaconda3/envs/aaj/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/home/khalil/anaconda3/envs/aaj/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/home/khalil/anaconda3/envs/aaj/lib/python3.6/site-packages/TTS/bin/convert_tacotron2_torch_to_tf.py", line 40, in <module>
    c = load_config(config_path)
  File "/home/khalil/anaconda3/envs/aaj/lib/python3.6/site-packages/TTS/utils/io.py", line 41, in load_config
    ext = os.path.splitext(config_path)[1]
  File "/home/khalil/anaconda3/envs/aaj/lib/python3.6/posixpath.py", line 122, in splitext
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType
(aaj) khalil@arabic-assistant:~/arabic-assistant$ python -m TTS.bin.convert_tacotron2_torch_to_tf.py --config_path /home/khalil/arabic-assistant/app/experiment_demo/tts_config.json --torch_model_path app/checkpoint/400-arabic-buckwalter-aug_text_input-Tacatron_ddc-November-21-2020.pth.tar --output_path app/checkpoint/tts_tac_model_tf.pkl
2021-03-16 16:29:30.037874: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
 > Using model: Tacotron2
2021-03-16 16:29:33.191075: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcuda.so.1
2021-03-16 16:29:33.952304: E tensorflow/stream_executor/cuda/cuda_driver.cc:314] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
2021-03-16 16:29:33.952415: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: arabic-assistant
2021-03-16 16:29:33.952431: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: arabic-assistant
2021-03-16 16:29:33.952635: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:200] libcuda reported version is: 450.102.4
2021-03-16 16:29:33.952674: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:204] kernel reported version is: 450.102.4
2021-03-16 16:29:33.952683: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:310] kernel version seems to match DSO: 450.102.4
2021-03-16 16:29:33.953211: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN)to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-03-16 16:29:33.961595: I tensorflow/core/platform/profile_utils/cpu_utils.cc:104] CPU Frequency: 2199995000 Hz
2021-03-16 16:29:33.962212: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55d33cb75e10 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2021-03-16 16:29:33.962245: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
(1, None, 80)
(1, None, 80)
[('embedding/embeddings:0', 'embedding.weight'),
 ('encoder/lstm/forward_lstm/lstm_cell_1/kernel:0',
  'encoder.lstm.weight_ih_l0'),
 ('encoder/lstm/forward_lstm/lstm_cell_1/recurrent_kernel:0',
  'encoder.lstm.weight_hh_l0'),
 ('encoder/lstm/backward_lstm/lstm_cell_2/kernel:0',
  'encoder.lstm.weight_ih_l0_reverse'),
 ('encoder/lstm/backward_lstm/lstm_cell_2/recurrent_kernel:0',
  'encoder.lstm.weight_hh_l0_reverse'),
 ('encoder/lstm/forward_lstm/lstm_cell_1/bias:0',
  ('encoder.lstm.bias_ih_l0', 'encoder.lstm.bias_hh_l0')),
 ('encoder/lstm/backward_lstm/lstm_cell_2/bias:0',
  ('encoder.lstm.bias_ih_l0_reverse', 'encoder.lstm.bias_hh_l0_reverse')),
 ('attention/v/kernel:0', 'decoder.attention.v.linear_layer.weight'),
 ('decoder/linear_projection/kernel:0',
  'decoder.linear_projection.linear_layer.weight'),
 ('decoder/stopnet/kernel:0', 'decoder.stopnet.1.linear_layer.weight'),
 ('encoder/convolutions_0/convolution1d/kernel:0',
  'encoder.convolutions.0.convolution1d.weight'),
 ('encoder/convolutions_0/convolution1d/bias:0',
  'encoder.convolutions.0.convolution1d.bias'),
 ('encoder/convolutions_0/batch_normalization/gamma:0',
  'encoder.convolutions.0.batch_normalization.weight'),
 ('encoder/convolutions_0/batch_normalization/beta:0',
  'encoder.convolutions.0.batch_normalization.bias'),
 ('encoder/convolutions_1/convolution1d/kernel:0',
  'encoder.convolutions.1.convolution1d.weight'),
 ('encoder/convolutions_1/convolution1d/bias:0',
  'encoder.convolutions.1.convolution1d.bias'),
 ('encoder/convolutions_1/batch_normalization/gamma:0',
  'encoder.convolutions.1.batch_normalization.weight'),
 ('encoder/convolutions_1/batch_normalization/beta:0',
  'encoder.convolutions.1.batch_normalization.bias'),
 ('encoder/convolutions_2/convolution1d/kernel:0',
  'encoder.convolutions.2.convolution1d.weight'),
 ('encoder/convolutions_2/convolution1d/bias:0',
  'encoder.convolutions.2.convolution1d.bias'),
 ('encoder/convolutions_2/batch_normalization/gamma:0',
  'encoder.convolutions.2.batch_normalization.weight'),
 ('encoder/convolutions_2/batch_normalization/beta:0',
  'encoder.convolutions.2.batch_normalization.bias'),
 ('encoder/convolutions_0/batch_normalization/moving_mean:0',
  'encoder.convolutions.0.batch_normalization.running_mean'),
 ('encoder/convolutions_0/batch_normalization/moving_variance:0',
  'encoder.convolutions.0.batch_normalization.running_var'),
 ('encoder/convolutions_1/batch_normalization/moving_mean:0',
  'encoder.convolutions.1.batch_normalization.running_mean'),
 ('encoder/convolutions_1/batch_normalization/moving_variance:0',
  'encoder.convolutions.1.batch_normalization.running_var'),
 ('encoder/convolutions_2/batch_normalization/moving_mean:0',
  'encoder.convolutions.2.batch_normalization.running_mean'),
 ('encoder/convolutions_2/batch_normalization/moving_variance:0',
  'encoder.convolutions.2.batch_normalization.running_var'),
 ('decoder/while/prenet/linear_layer_0/linear_layer/kernel:0',
  'decoder.prenet.linear_layers.0.linear_layer.weight'),
 ('decoder/while/prenet/linear_layer_1/linear_layer/kernel:0',
  'decoder.prenet.linear_layers.1.linear_layer.weight'),
 ('decoder/while/attention_rnn/kernel:0', 'decoder.attention_rnn.weight_ih'),
 ('decoder/while/attention_rnn/recurrent_kernel:0',
  'decoder.attention_rnn.weight_hh'),
 ('decoder/while/attention_rnn/bias:0', 'decoder.attention_rnn.bias_ih'),
 ('decoder/while/attention/query_layer/linear_layer/kernel:0',
  'decoder.attention.query_layer.linear_layer.weight'),
 ('decoder/attention/inputs_layer/linear_layer/kernel:0',
  'decoder.attention.inputs_layer.linear_layer.weight'),
 ('decoder/while/attention/v/linear_layer/kernel:0',
  'decoder.attention.v.linear_layer.weight'),
 ('decoder/while/attention/v/linear_layer/bias:0',
  'decoder.attention.v.linear_layer.bias'),
 ('decoder/while/attention/location_layer/location_conv1d/kernel:0',
  'decoder.attention.location_layer.location_conv1d.weight'),
 ('decoder/while/attention/location_layer/location_dense/kernel:0',
  'decoder.attention.location_layer.location_dense.linear_layer.weight'),
 ('decoder/while/decoder_rnn/kernel:0', 'decoder.decoder_rnn.weight_ih'),
 ('decoder/while/decoder_rnn/recurrent_kernel:0',
  'decoder.decoder_rnn.weight_hh'),
 ('decoder/while/decoder_rnn/bias:0', 'decoder.decoder_rnn.bias_ih'),
 ('decoder/while/linear_projection/linear_layer/kernel:0',
  'decoder.linear_projection.linear_layer.weight'),
 ('decoder/while/linear_projection/linear_layer/bias:0',
  'decoder.linear_projection.linear_layer.bias'),
 ('decoder/while/stopnet/linear_layer/kernel:0',
  'decoder.stopnet.1.linear_layer.weight'),
 ('decoder/while/stopnet/linear_layer/bias:0',
  'decoder.stopnet.1.linear_layer.bias'),
 ('postnet/convolutions_0/convolution1d/kernel:0',
  'postnet.convolutions.0.convolution1d.weight'),
 ('postnet/convolutions_0/convolution1d/bias:0',
  'postnet.convolutions.0.convolution1d.bias'),
 ('postnet/convolutions_0/batch_normalization/gamma:0',
  'postnet.convolutions.0.batch_normalization.weight'),
 ('postnet/convolutions_0/batch_normalization/beta:0',
  'postnet.convolutions.0.batch_normalization.bias'),
 ('postnet/convolutions_1/convolution1d/kernel:0',
  'postnet.convolutions.1.convolution1d.weight'),
 ('postnet/convolutions_1/convolution1d/bias:0',
  'postnet.convolutions.1.convolution1d.bias'),
 ('postnet/convolutions_1/batch_normalization/gamma:0',
  'postnet.convolutions.1.batch_normalization.weight'),
 ('postnet/convolutions_1/batch_normalization/beta:0',
  'postnet.convolutions.1.batch_normalization.bias'),
 ('postnet/convolutions_2/convolution1d/kernel:0',
  'postnet.convolutions.2.convolution1d.weight'),
 ('postnet/convolutions_2/convolution1d/bias:0',
  'postnet.convolutions.2.convolution1d.bias'),
 ('postnet/convolutions_2/batch_normalization/gamma:0',
  'postnet.convolutions.2.batch_normalization.weight'),
 ('postnet/convolutions_2/batch_normalization/beta:0',
  'postnet.convolutions.2.batch_normalization.bias'),
 ('postnet/convolutions_3/convolution1d/kernel:0',
  'postnet.convolutions.3.convolution1d.weight'),
 ('postnet/convolutions_3/convolution1d/bias:0',
  'postnet.convolutions.3.convolution1d.bias'),
 ('postnet/convolutions_3/batch_normalization/gamma:0',
  'postnet.convolutions.3.batch_normalization.weight'),
 ('postnet/convolutions_3/batch_normalization/beta:0',
  'postnet.convolutions.3.batch_normalization.bias'),
 ('postnet/convolutions_4/convolution1d/kernel:0',
  'postnet.convolutions.4.convolution1d.weight'),
 ('postnet/convolutions_4/convolution1d/bias:0',
  'postnet.convolutions.4.convolution1d.bias'),
 ('postnet/convolutions_4/batch_normalization/gamma:0',
  'postnet.convolutions.4.batch_normalization.weight'),
 ('postnet/convolutions_4/batch_normalization/beta:0',
  'postnet.convolutions.4.batch_normalization.bias'),
 ('postnet/convolutions_0/batch_normalization/moving_mean:0',
  'postnet.convolutions.0.batch_normalization.running_mean'),
 ('postnet/convolutions_0/batch_normalization/moving_variance:0',
  'postnet.convolutions.0.batch_normalization.running_var'),
 ('postnet/convolutions_1/batch_normalization/moving_mean:0',
  'postnet.convolutions.1.batch_normalization.running_mean'),
 ('postnet/convolutions_1/batch_normalization/moving_variance:0',
  'postnet.convolutions.1.batch_normalization.running_var'),
 ('postnet/convolutions_2/batch_normalization/moving_mean:0',
  'postnet.convolutions.2.batch_normalization.running_mean'),
 ('postnet/convolutions_2/batch_normalization/moving_variance:0',
  'postnet.convolutions.2.batch_normalization.running_var'),
 ('postnet/convolutions_3/batch_normalization/moving_mean:0',
  'postnet.convolutions.3.batch_normalization.running_mean'),
 ('postnet/convolutions_3/batch_normalization/moving_variance:0',
  'postnet.convolutions.3.batch_normalization.running_var'),
 ('postnet/convolutions_4/batch_normalization/moving_mean:0',
  'postnet.convolutions.4.batch_normalization.running_mean'),
 ('postnet/convolutions_4/batch_normalization/moving_variance:0',
  'postnet.convolutions.4.batch_normalization.running_var')]
['embedding.weight',
 'encoder.convolutions.0.batch_normalization.num_batches_tracked',
 'encoder.convolutions.1.batch_normalization.num_batches_tracked',
 'encoder.convolutions.2.batch_normalization.num_batches_tracked',
 'encoder.lstm.weight_ih_l0',
 'encoder.lstm.weight_hh_l0',
 'encoder.lstm.bias_ih_l0',
 'encoder.lstm.bias_hh_l0',
 'encoder.lstm.weight_ih_l0_reverse',
 'encoder.lstm.weight_hh_l0_reverse',
 'encoder.lstm.bias_ih_l0_reverse',
 'encoder.lstm.bias_hh_l0_reverse',
 'decoder.attention_rnn.bias_hh',
 'decoder.decoder_rnn.bias_hh',
 'postnet.convolutions.0.batch_normalization.num_batches_tracked',
 'postnet.convolutions.1.batch_normalization.num_batches_tracked',
 'postnet.convolutions.2.batch_normalization.num_batches_tracked',
 'postnet.convolutions.3.batch_normalization.num_batches_tracked',
 'postnet.convolutions.4.batch_normalization.num_batches_tracked',
 'coarse_decoder.prenet.linear_layers.0.linear_layer.weight',
 'coarse_decoder.prenet.linear_layers.1.linear_layer.weight',
 'coarse_decoder.attention_rnn.weight_ih',
 'coarse_decoder.attention_rnn.weight_hh',
 'coarse_decoder.attention_rnn.bias_ih',
 'coarse_decoder.attention_rnn.bias_hh',
 'coarse_decoder.attention.query_layer.linear_layer.weight',
 'coarse_decoder.attention.inputs_layer.linear_layer.weight',
 'coarse_decoder.attention.v.linear_layer.weight',
 'coarse_decoder.attention.v.linear_layer.bias',
 'coarse_decoder.attention.location_layer.location_conv1d.weight',
 'coarse_decoder.attention.location_layer.location_dense.linear_layer.weight',
 'coarse_decoder.decoder_rnn.weight_ih',
 'coarse_decoder.decoder_rnn.weight_hh',
 'coarse_decoder.decoder_rnn.bias_ih',
 'coarse_decoder.decoder_rnn.bias_hh',
 'coarse_decoder.linear_projection.linear_layer.weight',
 'coarse_decoder.linear_projection.linear_layer.bias',
 'coarse_decoder.stopnet.1.linear_layer.weight',
 'coarse_decoder.stopnet.1.linear_layer.bias']
 > Passing weights from Torch to TF ...
 | > embedding/embeddings:0 <-- embedding.weight
 | > encoder/convolutions_0/convolution1d/kernel:0 <-- encoder.convolutions.0.convolution1d.weight
 | > encoder/convolutions_0/convolution1d/bias:0 <-- encoder.convolutions.0.convolution1d.bias
 | > encoder/convolutions_0/batch_normalization/gamma:0 <-- encoder.convolutions.0.batch_normalization.weight
 | > encoder/convolutions_0/batch_normalization/beta:0 <-- encoder.convolutions.0.batch_normalization.bias
 | > encoder/convolutions_1/convolution1d/kernel:0 <-- encoder.convolutions.1.convolution1d.weight
 | > encoder/convolutions_1/convolution1d/bias:0 <-- encoder.convolutions.1.convolution1d.bias
 | > encoder/convolutions_1/batch_normalization/gamma:0 <-- encoder.convolutions.1.batch_normalization.weight
 | > encoder/convolutions_1/batch_normalization/beta:0 <-- encoder.convolutions.1.batch_normalization.bias
 | > encoder/convolutions_2/convolution1d/kernel:0 <-- encoder.convolutions.2.convolution1d.weight
 | > encoder/convolutions_2/convolution1d/bias:0 <-- encoder.convolutions.2.convolution1d.bias
 | > encoder/convolutions_2/batch_normalization/gamma:0 <-- encoder.convolutions.2.batch_normalization.weight
 | > encoder/convolutions_2/batch_normalization/beta:0 <-- encoder.convolutions.2.batch_normalization.bias
 | > encoder/lstm/forward_lstm/lstm_cell_1/kernel:0 <-- encoder.lstm.weight_ih_l0
 | > encoder/lstm/forward_lstm/lstm_cell_1/recurrent_kernel:0 <-- encoder.lstm.weight_hh_l0
 | > encoder/lstm/forward_lstm/lstm_cell_1/bias:0 <-- ('encoder.lstm.bias_ih_l0', 'encoder.lstm.bias_hh_l0')
 | > encoder/lstm/backward_lstm/lstm_cell_2/kernel:0 <-- encoder.lstm.weight_ih_l0_reverse
 | > encoder/lstm/backward_lstm/lstm_cell_2/recurrent_kernel:0 <-- encoder.lstm.weight_hh_l0_reverse
 | > encoder/lstm/backward_lstm/lstm_cell_2/bias:0 <-- ('encoder.lstm.bias_ih_l0_reverse', 'encoder.lstm.bias_hh_l0_reverse')
 | > encoder/convolutions_0/batch_normalization/moving_mean:0 <-- encoder.convolutions.0.batch_normalization.running_mean
 | > encoder/convolutions_0/batch_normalization/moving_variance:0 <-- encoder.convolutions.0.batch_normalization.running_var
 | > encoder/convolutions_1/batch_normalization/moving_mean:0 <-- encoder.convolutions.1.batch_normalization.running_mean
 | > encoder/convolutions_1/batch_normalization/moving_variance:0 <-- encoder.convolutions.1.batch_normalization.running_var
 | > encoder/convolutions_2/batch_normalization/moving_mean:0 <-- encoder.convolutions.2.batch_normalization.running_mean
 | > encoder/convolutions_2/batch_normalization/moving_variance:0 <-- encoder.convolutions.2.batch_normalization.running_var
 | > decoder/while/prenet/linear_layer_0/linear_layer/kernel:0 <-- decoder.prenet.linear_layers.0.linear_layer.weight
 | > decoder/while/prenet/linear_layer_1/linear_layer/kernel:0 <-- decoder.prenet.linear_layers.1.linear_layer.weight
 | > decoder/while/attention_rnn/kernel:0 <-- decoder.attention_rnn.weight_ih
 | > decoder/while/attention_rnn/recurrent_kernel:0 <-- decoder.attention_rnn.weight_hh
 | > decoder/while/attention_rnn/bias:0 <-- decoder.attention_rnn.bias_ih
Traceback (most recent call last):
  File "/home/khalil/anaconda3/envs/aaj/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/home/khalil/anaconda3/envs/aaj/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/home/khalil/anaconda3/envs/aaj/lib/python3.6/site-packages/TTS/bin/convert_tacotron2_torch_to_tf.py", line 121, in <module>
    tf_vars = transfer_weights_torch_to_tf(tf_vars, dict(var_map), state_dict)
  File "/home/khalil/anaconda3/envs/aaj/lib/python3.6/site-packages/TTS/tts/tf/utils/convert_torch_to_tf_utils.py", line 70, in transfer_weights_torch_to_tf
    assert len(bias_vectors) == 2
AssertionError
```
I searched for this issue here and on your discussion forum and didn't find anything related.
Any ideas about this problems? 
Thank you

**Comment by khalilRhouma** [comment]
I tried to debug this code and what I found is that `bias_vectors` in [this line](https://github.com/mozilla/TTS/blob/master/TTS/tts/tf/utils/convert_torch_to_tf_utils.py#L69)  will match 4 layers not 2.
 So, for that this assertion in [ligne 70](https://github.com/mozilla/TTS/blob/master/TTS/tts/tf/utils/convert_torch_to_tf_utils.py#L70) it should be changed to  `assert len(bias_vectors) == 4`.
  For my case, I change it like this and I got the TF checkpoint and the inference works as expected.
