### ISSUE TITLE
UnicodeDecodeError when training on custom dataset

### ISSUE THREAD

**Issue by n2pakbong** [mozilla/TTS#689]
Hello and thank you for this amazing project !  

I get the following error when trying to launch a training with my custom dataset in MAILABS format with the command  
 `python TTS/bin/train_tacotron.py --config_path TTS/tts/configs/config_pando_ft.json --restore_path /scratch/students/n.tepakbong/models/best_model.pth.tar` :  
```
Traceback (most recent call last):
  File "TTS/bin/train_tacotron.py", line 688, in <module>
    c = load_config(args.config_path)
  File "/home/promo21/n.tepakbong/TTS/TTS/utils/io.py", line 46, in load_config
    data = read_json_with_comments(config_path)
  File "/home/promo21/n.tepakbong/TTS/TTS/utils/io.py", line 26, in read_json_with_comments
    input_str = f.read()
  File "/home/promo21/n.tepakbong/.conda/envs/myenv/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf8 in position 2797: invalid start byte
```  

I tried forcing Python encoding with UTF-8 using `export PYTHONIOENCODING=utf-8` or `set PYTHONUTF8=1` but  I still get the same error.  
My config file mostly has the default settings, I just added the correct paths for my setup, but if needed I can share it too.  

Does anyone have any idea ?

**Comment by n2pakbong** [comment]
Ok so the fix was actually quite simple, I just had to do the following modifications in the file `TTS/TTS/utils/io.py` :  

- Change `config_lines = open(config_file, "r").readlines()`  to `config_lines = open(config_file, "r", encoding="ISO-8859-1").readlines()` line 32
- Change `with open(json_path, "r") as f:` to `with open(json_path, "r", encoding="ISO-8859-1") as f:` line 21

Now everything seems to be working properly !
