### ISSUE TITLE
Can't run on Windows

### ISSUE THREAD

**Issue by hohuynhminhhieu** [mozilla/TTS#713]
Hi, I don't know why the Mozilla TTS on Windows, it keeps saying this:
Traceback (most recent call last):
  File "TTS/bin/train_tacotron.py", line 697, in <module>
    OUT_PATH = create_experiment_folder(c.output_path, c.run_name, args.debug)
  File "c:\mozillatts_eng\TTS\utils\generic_utils.py", line 47, in create_experiment_folder
    commit_hash = get_commit_hash()
  File "c:\mozillatts_eng\TTS\utils\generic_utils.py", line 33, in get_commit_hash
    ['git', 'rev-parse', '--short', 'HEAD']).decode().strip()
  File "C:\Users\AH\.conda\envs\mozillaTTS_eng\lib\subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "C:\Users\AH\.conda\envs\mozillaTTS_eng\lib\subprocess.py", line 488, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\AH\.conda\envs\mozillaTTS_eng\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "C:\Users\AH\.conda\envs\mozillaTTS_eng\lib\subprocess.py", line 1207, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
Could you guys checking on this for me? Thank you.

**Comment by erogol** [comment]
This project is not maintained anymore. Feel free to move over Coqui-TTS https://github.com/coqui-ai/TTS which is the actively developed hard fork.
