### ISSUE TITLE
ValueError: not enough values to unpack (expected 4, got 1)

### ISSUE THREAD

**Issue by wanghaisheng** [mozilla/TTS#725]
```
pip install TTS
dubo@LAPTOP-I2R9VG58 MINGW64 /d/Download/audio-visual/auto_video-jigsaw/tts/coqui-tts
$ ls -ll
total 1194676
-rw-r--r-- 1 dubo 197121     11584  8月 27 09:01 multispeaker_vctk_tacotron2_ddc_wavegrad.py
-rw-r--r-- 1 dubo 197121 417541353  8月 16 23:38 speakers.json
-rw-r--r-- 1 dubo 197121     12586  8月 16 23:36 tts_config.json
-rw-r--r-- 1 dubo 197121 615904210  8月 16 23:35 tts_model.pth.tar
-rw-r--r-- 1 dubo 197121     10450  8月 16 23:36 tts_scale_stats.npy
-rw-r--r-- 1 dubo 197121      6076  8月 16 23:39 vocoder_config.json
-rw-r--r-- 1 dubo 197121 189835155  8月 16 23:40 vocoder_model.pth.tar
-rw-r--r-- 1 dubo 197121     10471  8月 16 23:38 vocoder_scale_stats.npy
(tts)
dubo@LAPTOP-I2R9VG58 MINGW64 /d/Download/audio-visual/auto_video-jigsaw/tts/coqui-tts
$ tts --text "Text for TTS"     --model_path tts_model.pth.tar     --config_path tts_config.json     --vocoder_name "vocoder_model.pth.tar"     --out_path speech.wav
Traceback (most recent call last):
  File "d:\program files\anaconda3\envs\tts\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "d:\program files\anaconda3\envs\tts\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\Program Files\anaconda3\envs\tts\Scripts\tts.exe\__main__.py", line 7, in <module>
  File "d:\program files\anaconda3\envs\tts\lib\site-packages\TTS\bin\synthesize.py", line 209, in main
    vocoder_path, vocoder_config_path, _ = manager.download_model(args.vocoder_name)
  File "d:\program files\anaconda3\envs\tts\lib\site-packages\TTS\utils\manage.py", line 99, in download_model
    model_type, lang, dataset, model = model_name.split("/")
ValueError: not enough values to unpack (expected 4, got 1)
```

**Comment by mehmetsolves** [comment]
I also got the same error. Did you solve the error?

**Comment by wanghaisheng** [comment]
no
