### ISSUE TITLE
Fixed installation instructions for fresh Ubuntu 18

### ISSUE THREAD

**Issue by stefan-reich** [mozilla/TTS#728]
Long story short: The installation instructions from https://github.com/mozilla/TTS/tree/dev#install-tts are incomplete (or actually wrong, as pip3 needs to be used).

The complete instructions for Ubuntu 18.04 are:

```
sudo apt install python3-pip
sudo pip3 install --upgrade pip # get PIP 21
sudo pip3 install TTS
```

Should I make this a pull request?

**Comment by xandark** [comment]
> sudo apt install python3-pip
> sudo pip3 install --upgrade pip # get PIP 21
> sudo pip3 install TTS

When I tried this on my Ubuntu 20.04 system, it downloaded and installed successfully, but I received this message at the end:

`WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv`

And when I subsequently tried to run tts, I got this error:

```
Traceback (most recent call last):
  File "/usr/local/bin/tts", line 5, in <module>
    from TTS.bin.synthesize import main
  File "/usr/local/lib/python3.8/dist-packages/TTS/bin/synthesize.py", line 12, in <module>
    from TTS.utils.synthesizer import Synthesizer
  File "/usr/local/lib/python3.8/dist-packages/TTS/utils/synthesizer.py", line 10, in <module>
    from TTS.tts.utils.speakers import SpeakerManager
  File "/usr/local/lib/python3.8/dist-packages/TTS/tts/utils/speakers.py", line 13, in <module>
    from TTS.utils.audio import AudioProcessor
  File "/usr/local/lib/python3.8/dist-packages/TTS/utils/audio.py", line 5, in <module>
    import pyworld as pw
  File "/usr/local/lib/python3.8/dist-packages/pyworld/__init__.py", line 7, in <module>
    from .pyworld import *
  File "pyworld/pyworld.pyx", line 1, in init pyworld.pyworld
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject
```

I think it's because I have the python3-numpy package installed on my system.

As a side note, I tried installing TTS as --user, but I got this snarl of an error message:

```
ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-qdop8po2/unidic-lite/setup.py'"'"'; __file__='"'"'/tmp/pip-install-qdop8po2/unidic-lite/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-59b6rtnq/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/michael/.local/include/python3.8/unidic-lite
         cwd: /tmp/pip-install-qdop8po2/unidic-lite/
    Complete output (15 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib
    creating build/lib/unidic_lite
    copying unidic_lite/unidic.py -> build/lib/unidic_lite
    copying unidic_lite/__init__.py -> build/lib/unidic_lite
    creating build/lib/unidic_lite/dicdir
    copying unidic_lite/dicdir/version -> build/lib/unidic_lite/dicdir
    copying unidic_lite/dicdir/unk.dic -> build/lib/unidic_lite/dicdir
    copying unidic_lite/dicdir/unidic-mecab.pdf -> build/lib/unidic_lite/dicdir
    copying unidic_lite/dicdir/sys.dic -> build/lib/unidic_lite/dicdir
    copying unidic_lite/dicdir/right-id.def -> build/lib/unidic_lite/dicdir
    error: could not write to 'build/lib/unidic_lite/dicdir/right-id.def': No space left on device
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-qdop8po2/unidic-lite/setup.py'"'"'; __file__='"'"'/tmp/pip-install-qdop8po2/unidic-lite/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-59b6rtnq/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/michael/.local/include/python3.8/unidic-lite Check the logs for full command output.
```

I'm not sure why it was saying "No space left on device" in this case, maybe it's referring to /tmp? But that was running pip3 as --user.

I think the best way forward is to try to install in a virtualenv as the initial warning mentioned.

**Comment by xandark** [comment]
I removed all the packages that were installed with the `sudo pip3 install TTS` method and instead created an venv, but I'm still getting the same "No space left on device" error when building unidic-lite...

```
cd .local/
python3 -m venv mozilla-tts
cd mozilla-tts
source bin/activate.fish
python3 -m pip install TTS
```

```
Building wheels for collected packages: unidic-lite
  Building wheel for unidic-lite (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/michael/.local/mozilla-tts/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-861zwpsk/unidic-lite/setup.py'"'"'; __file__='"'"'/tmp/pip-install-861zwpsk/unidic-lite/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-fuw9b8qk
       cwd: /tmp/pip-install-861zwpsk/unidic-lite/
  Complete output (6 lines):
  usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: setup.py --help [cmd1 cmd2 ...]
     or: setup.py --help-commands
     or: setup.py cmd --help
  
  error: invalid command 'bdist_wheel'
  ----------------------------------------
  ERROR: Failed building wheel for unidic-lite
  Running setup.py clean for unidic-lite
Failed to build unidic-lite
Installing collected packages: llvmlite, numpy, numba, coqpit, gruut-ipa, docopt, num2words, pytz, Babel, python-crfsuite, six, jsonlines, gruut-lang-cs, gruut-lang-de, gruut-lang-es, gruut-lang-fr, gruut-lang-it, gruut-lang-nl, gruut-lang-pt, gruut-lang-ru, gruut-lang-sv, gruut, inflect, protobuf, tensorboardX, scipy, joblib, threadpoolctl, scikit-learn, pynndescent, umap-learn, decorator, pycparser, cffi, soundfile, resampy, audioread, pyparsing, packaging, urllib3, certifi, idna, charset-normalizer, PySocks, requests, appdirs, pooch, librosa, pypinyin, tqdm, pyyaml, typing-extensions, torch, pysbd, cython, pyworld, python-dateutil, pandas, jieba, click, itsdangerous, MarkupSafe, Jinja2, Werkzeug, flask, unidic-lite, anyascii, filelock, gdown, mecab-python3, fsspec, kiwisolver, cycler, pillow, matplotlib, TTS
ERROR: Could not install packages due to an EnvironmentError: [Errno 28] No space left on device
```

**Comment by xandark** [comment]
Okay, one last comment on how to get it to install on my Ubuntu 20.04 system. 

Installing tts to a venv requires /tmp having **more** than 4GB, which is what my system has allocated to it. So when I bumped /tmp up to 8GB, it worked: `sudo mount -o remount,size=8G /tmp/` . That fixes the "No space left on device" errors.

Installing tts to ~/.local/bin with a conflicting python3-numpy package installed on my system meant that I had to issue a `pip install --upgrade numpy` to install a newer NumPy to ~/.local/bin, which ~/.local/bin/tts will use.

**Comment by xandark** [comment]
This has been automatically closed, but the issue has not been fixed.

 On the README.md main page, there is this:

> Install TTS
> TTS supports python >= 3.6, <3.9.
> 
> If you are only interested in [synthesizing speech](https://github.com/mozilla/TTS/tree/dev#example-synthesizing-speech-on-terminal-using-the-released-models) with the released TTS models, installing from PyPI is the easiest option.
> 
> pip install TTS

But that installation instruction will fail for some people. It should say:

> Ubuntu 20.04 instructions:
> 
> cd .local/
> python3 -m venv mozilla-tts
> cd mozilla-tts
> source bin/activate
> python3 -m pip install --upgrade TTS numpy
> 
> Numpy should be installed from PIP instead of using the system python3-numpy package from Debian/Ubuntu 20.04. Installing tts to a venv requires /tmp having more than 4GB, or installation will encounter "No space left on device" errors. To bump /tmp up to 8GB, do this: sudo mount -o remount,size=8G /tmp/
>
