### ISSUE TITLE
Resource temporarily unavailable

### ISSUE THREAD

**Issue by bphd** [mozilla/TTS#744]
<b>Questions</b> will not be answered here!!

Help is much more valuable if it's shared publicly, so that more people can benefit from it.

Please consider posting on [TTS Discourse](https://discourse.mozilla.org/c/tts) page or matrix [chat room](https://matrix.to/#/!KTePhNahjgiVumkqca:matrix.org?via=matrix.org) if your issue is not directly related to TTS development (Bugs, code updates etc.).

You can also check https://github.com/mozilla/TTS/wiki/FAQ for common questions and answers.

Happy posting!

https://discourse.mozilla.org/c/tts

```shell
$ tts --text 'Bonjour' --model_name "`tts --list_models | grep \ $(($RANDOM%31)): | cut -d ' ' -f 3`" --vocoder_name "`tts --list_models | grep \ $(($RANDOM%31)): | cut -d ' ' -f 3`" --out_path $path/testAudio.mp3
++ tts --list_models
++ grep --color=auto ' 19:'
++ cut -d ' ' -f 3
++ tts --list_models
++ grep --color=auto ' 26:'
++ cut -d ' ' -f 3
+ tts --text Bonjour --model_name  tts_models/ja/kokoro/tacotron2-DDC --vocoder_name vocoder_models/en/vctk/hifigan_v2 --out_path /path/testAuudio.mp3
 > Downloading model to /home/ubuntu/.local/share/tts/tts_models--ja--kokoro--tacotron2-DDC
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
BlockingIOError: [Errno 11] Resource temporarily unavailable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 376, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 996, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 314, in connect
    conn = self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 171, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7fa3766e61f0>: Failed to establish a new connection: [Errno 11] Resource temporarily unavailable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 719, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='coqui.gateway.scarf.sh', port=443): Max retries exceeded with url: /v0.0.12/vocoder_model--en--vctk--hifigan_v2.zip (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fa3766e61f0>: Failed to establish a new connection: [Errno 11] Resource temporarily unavailable'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/tts", line 8, in <module>
    sys.exit(main())
  File "/home/ubuntu/.local/lib/python3.8/site-packages/TTS/bin/synthesize.py", line 205, in main
    model_path, config_path, model_item = manager.download_model(args.model_name)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/TTS/utils/manage.py", line 109, in download_model
    self._download_zip_file(model_item["github_rls_url"], output_path)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/TTS/utils/manage.py", line 160, in _download_zip_file
    r = requests.get(file_url)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='coqui.gateway.scarf.sh', port=443): Max retries exceeded with url: /v0.0.12/vocoder_model--en--vctk--hifigan_v2.zip (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fa3766e61f0>: Failed to establish a new connection: [Errno 11] Resource temporarily unavailable'))
```

**Comment by bphd** [comment]
After a lot of tries, it managed to download that

 ```shell
$ du /home/ubuntu/.local/share/tts/tts_models--en--ek1--tacotron2/* /home/ubuntu/.local/share/tts/tts_models--en--ljspeech--tacotron2-DCA/* /home/ubuntu/.local/share/tts/vocoder_models--en--ljspeech--univnet/*
4       /home/ubuntu/.local/share/tts/tts_models--en--ek1--tacotron2/config.json
339036  /home/ubuntu/.local/share/tts/tts_models--en--ek1--tacotron2/model_file.pth.tar
8       /home/ubuntu/.local/share/tts/tts_models--en--ljspeech--tacotron2-DCA/config.json
331260  /home/ubuntu/.local/share/tts/tts_models--en--ljspeech--tacotron2-DCA/model_file.pth.tar
12      /home/ubuntu/.local/share/tts/tts_models--en--ljspeech--tacotron2-DCA/scale_stats.npy
0       /home/ubuntu/.local/share/tts/vocoder_models--en--ljspeech--univnet/__MACOSX/vocoder_models--en--ljspeech--univnet_v2
0       /home/ubuntu/.local/share/tts/vocoder_models--en--ljspeech--univnet/__MACOSX
4       /home/ubuntu/.local/share/tts/vocoder_models--en--ljspeech--univnet/config.json
659284  /home/ubuntu/.local/share/tts/vocoder_models--en--ljspeech--univnet/model_file.pth.tar
12      /home/ubuntu/.local/share/tts/vocoder_models--en--ljspeech--univnet/scale_stats.npy
$ md5sum /home/ubuntu/.local/share/tts/tts_models--en--ek1--tacotron2/* /home/ubuntu/.local/share/tts/tts_models--en--ljspeech--tacotron2-DCA/* /home/ubuntu/.local/share/tts/vocoder_models--en--ljspeech--univnet/*
b0e7dfdedb52d39ed1341a3bed2af5da  /home/ubuntu/.local/share/tts/tts_models--en--ek1--tacotron2/config.json
3e69582513a0a53175b49fa4e7c656d8  /home/ubuntu/.local/share/tts/tts_models--en--ek1--tacotron2/model_file.pth.tar
cbdfb2baf28a3c61778bf858ecf01371  /home/ubuntu/.local/share/tts/tts_models--en--ljspeech--tacotron2-DCA/config.json
7a5a733a494128e121a0ac9150240096  /home/ubuntu/.local/share/tts/tts_models--en--ljspeech--tacotron2-DCA/model_file.pth.tar
83b56852274b41b6fc30e55517b2697d  /home/ubuntu/.local/share/tts/tts_models--en--ljspeech--tacotron2-DCA/scale_stats.npy
md5sum: /home/ubuntu/.local/share/tts/vocoder_models--en--ljspeech--univnet/__MACOSX: Is a directory
b9726ead2e3fc238356b674dd69b7b31  /home/ubuntu/.local/share/tts/vocoder_models--en--ljspeech--univnet/config.json
f86cd348b899c4623fcf65b917334438  /home/ubuntu/.local/share/tts/vocoder_models--en--ljspeech--univnet/model_file.pth.tar
4a006a3a1fbd82fd2dbaf3fd8ea56a6e  /home/ubuntu/.local/share/tts/vocoder_models--en--ljspeech--univnet/scale_stats.npy
```

But that isn't enough to work with the software and/or isn't the models that I want
